import { Scheme, Campaign, Article, SupportGroup, ChildVideo, AppEvent, AppLanguage } from './types';

// English Strings
const EN_STRINGS = {
  dashboard: 'Dashboard',
  mood_board: 'Mood Board',
  navigator: 'Navigator',
  navigator_header: 'Visionary Care Navigator',
  navigator_sub: 'Precision-mapped clinical roadmaps integrated with institutional protocols and real-time resource grounding.',
  med_scanner: 'Meds Scanner',
  meds_scanner_header: 'Vision-AI Med Scanner',
  meds_scanner_sub: 'Grounded pharmaceutical analysis of chemical compounds, safety warnings, and clinical instructions.',
  doc_intel: 'Doc Intel',
  doc_intel_header: 'Doc Intel Vault',
  doc_intel_sub: 'Securely store reports and let AI explain context',
  insights: 'Insights Hub',
  insights_header: 'Insights Hub',
  insights_sub: 'Clinical news verified portals and expert guides',
  meetups: 'Survivor Meetups',
  trust: 'Trust',
  hero_hub: 'Hero HQ',
  hero_garden: 'Hero Garden',
  hero_tasks: 'Power Tasks',
  emergency_sos: 'EMERGENCY SOS',
  impact_hub: 'Impact Hub',
  impact_hub_header: 'Impact Hub',
  impact_hub_sub: 'Witness social impact and support care navigation',
  welcome: 'Welcome',
  give_aid: 'Support Impact',
  nursing_aid: 'Nursing Aid',
  settings: 'Settings',
  companion: 'AI Companion',
  finder: 'Finder',
  finder_header: 'Resource Finder',
  finder_sub: 'Locate oncology resources and nearby pharmacies',
  schemes: 'Aid Schemes',
  schemes_header: 'Aid Schemes',
  schemes_sub: 'Navigate government paperwork with ease. Verified financial aid.',
  survivors_hub: 'Survivors Hub',
  survivors_hub_header: 'Survivors Hub',
  survivors_hub_sub: 'Your Resilience Sanctuary for life after cancer.',
  skills_hub: 'Skills Hub',
  skills_hub_header: 'Clinical Skills Hub',
  skills_hub_sub: 'Master home-care tasks with AI-guided tutorials.',
  saved_sanctuary: 'Saved Sanctuary',
  saved_sanctuary_header: 'Saved Sanctuary',
  saved_sanctuary_sub: 'Your curated collection of important guides and resources.',
  welcome_home: 'Welcome Home Friend',
  unified_sanctuary: 'Unified Care Sanctuary',
  comfort_recovery_desc: 'Easy to use tools for your comfort and recovery',
  clinical_logic_desc: 'A gentle sanctuary for clinical logic and emotional resilience.',
  gen_brief: 'Generate Doctor Brief',
  search_placeholder: 'Search Sanctuary...',
  select_perspective: 'Select your Perspective',
  select_desc: 'Choose your journey so we can personalize every bit of support from magic stories for kids to clinical aid for patients.',
  role_patient: 'Patient',
  role_caregiver: 'Caregiver',
  role_hero: 'Hero Kid',
  role_donor: 'Supporter',
  role_survivor: 'Survivor',
  role_patient_desc: 'Clinical navigation nursing aid easy read guides and AI companions',
  role_caregiver_desc: 'Full resource hub for guardians and family support',
  role_hero_desc: 'A gamified magic quest with Buddy the hero companion',
  role_donor_desc: 'Witness social impact and support care navigation No fees Pure impact',
  role_survivor_desc: 'Follow up monitoring scan anxiety support and life after cancer guides',
  news_tab: 'News',
  guides_tab: 'Guides',
  portals_tab: 'Portals',
  back: 'Back',
  continue: 'Continue',
  save: 'Save',
  add: 'Add',
  delete: 'Delete',
  logout: 'Logout',
  sync: 'Sync',
  hero_quests: 'Super Quests',
  daily_missions: 'Complete missions for XP',
  buddy_chat: 'Talk to Buddy',
  buddy_desc: 'Your magic AI friend',
  magic_studio: 'Magic Studio',
  magic_desc: 'Paint your dreams',
  hero_cinema: 'Hero Cinema',
  cinema_choice: 'Watch & Learn',
  stay_brave: 'Stay Brave',
  magic_energy: 'Magic Energy',
  next_level: 'Next Level',
  symptom_log: 'Symptom Log',
  symptom_log_header: 'Symptom Log',
  symptom_log_sub: 'Track physical changes to share with your oncology team.',
  track_physical: 'Track physical trends',
  daily_sanctuary_focus: 'Daily Sanctuary Focus',
  hero_welcome: 'Welcome to Hero HQ!',
  hero_level: 'Hero Level',
  xp_to_go: 'XP to next level',
  open_studio: 'Open Studio',
  watch_movie: 'Watch Movie',
  start_quest: 'Start Quest',
  sticker_vault: 'Sticker Vault',
  commander_hub: 'Commander Hub',
  collected: 'Collected',
  locked: 'Locked',
  tap_to_open: 'TAP TO OPEN',
  unlocked: 'UNLOCKED',
  mark_complete: 'Mark Complete',
  completed: 'Completed',
  magic_fact: 'Magic Fact',
  mystery_box: 'Mystery Box',
  mystery_box_title: 'The Mystery Box!',
  mystery_box_desc: 'A special hero treasure is hidden inside. Want to see it?',
  new_sticker: 'New Sticker!',
  bravery_sparkle: 'Your bravery just got a new sparkle!',
  level_up: 'Level Up!',
  reached_level: 'Reached Level',
  continue_quest: 'Continue Quest',
  memory_quest: 'Memory Quest',
  train_brain: 'Train Your Brain',
  later: 'Later',
  open_now: 'Open Now',
  xp_awarded: 'XP AWARDED',
  magic_energy_needed: 'XP to Next Power-up',
  hero_quest_banner: 'The Hero Quest',
  cinema_banner: 'Magic moments and brave stories for your recovery mission.',
  scan_history: 'Scan History',
  read_analysis: 'Read Analysis',
  add_reminder: 'Add Reminder',
  dismiss: 'Dismiss',
  analyzing: 'Analyzing Medicine...',
  vision_logic: 'Gemini Pro Vision Logic',
  analyze_symptoms: 'Analyze Patterns',
  generating_insights: 'Finding Trends...',
  symptom_patterns_header: 'Symptom Intelligence',
  symptom_patterns_sub: 'Discover clinical patterns in your log to discuss with your doctor.',
  'vid-io2_title': 'Inside Out 2 - Stay Brave',
  'vid-io2_desc': 'A magical journey into understanding new emotions and staying brave through difficult changes.',
  'vid-dino_title': 'The Good Dinosaur',
  'vid-dino_desc': 'Arlo learns that bravery is taking steps even when you are scared of the unknown.',
  'vid-scarlett_title': 'Scarlett',
  'vid-scarlett_desc': 'A beautiful story about a brave girl finding her magic again through courage and dance.',
  'vid-piper_title': 'Piper',
  'vid-piper_desc': 'A tiny hero overcomes the big waves to find something wonderful in the smallest of things.'
};

// Hindi Strings
const HI_STRINGS = {
  dashboard: 'डैशबोर्ड',
  mood_board: 'मूड बोर्ड',
  navigator: 'नेविगेटर',
  navigator_header: 'विज़नरी केयर नेविगेटर',
  navigator_sub: 'संस्थागत प्रोटोकॉल और वास्तविक समय के संसाधन ग्राउंडिंग के साथ सटीक-मैप्ड क्लीनिकल रोडमैप।',
  med_scanner: 'दवा स्कैनर',
  meds_scanner_header: 'विज़न-AI मेड स्कैनर',
  meds_scanner_sub: 'रासायनिक यौगिकों, सुरक्षा चेतावनियों और क्लीनिकल निर्देशों का विस्तृत विश्लेषण।',
  doc_intel: 'डॉक इंटेल',
  doc_intel_header: 'डॉक इंटेल वॉल्ट',
  doc_intel_sub: 'रिपोर्ट्स सुरक्षित रूप से स्टोर करें और AI को संदर्भ समझाने दें',
  insights: 'इनसाइट्स हब',
  insights_header: 'इनसाइट्स हब',
  insights_sub: 'क्लीनिकल समाचार, सत्यापित पोर्टल और विशेषज्ञ गाइड',
  meetups: 'सर्वाइवर मीटअप',
  trust: 'ट्रस्ट',
  hero_hub: 'हीरो मुख्यालय',
  hero_garden: 'हीरो गार्डन',
  hero_tasks: 'पावर टास्क',
  emergency_sos: 'आपातकालीन SOS',
  impact_hub: 'इम्पैक्ट हब',
  impact_hub_header: 'इम्पैक्ट हब',
  impact_hub_sub: 'सामाजिक प्रभाव देखें और देखभाल नेविगेशन का समर्थन करें',
  welcome: 'स्वागत है',
  give_aid: 'सहायता दें',
  nursing_aid: 'नर्सिंग सहायता',
  settings: 'सेटिंग्स',
  companion: 'AI साथी',
  finder: 'खोजक',
  finder_header: 'संसाधन खोजक',
  finder_sub: 'ऑन्कोलॉजी संसाधन और नजदीकी फार्मेसियों का पता लगाएं',
  schemes: 'सहायता योजनाएं',
  schemes_header: 'सहायता योजनाएं',
  schemes_sub: 'सरकारी कागजी कार्रवाई को आसानी से नेविगेट करें। सत्यापित वित्तीय सहायता।',
  survivors_hub: 'सर्वाइवर्स हब',
  survivors_hub_header: 'सर्वाइवर्स हब',
  survivors_hub_sub: 'कैंसर के बाद जीवन के लिए आपका लचीलापन अभयारण्य।',
  skills_hub: 'कौशल हब',
  skills_hub_header: 'क्लीनिकल स्किल्स हब',
  skills_hub_sub: 'AI-निर्देशित ट्यूटोरियल के साथ घरेलू देखभाल कार्यों में महारत हासिल करें।',
  saved_sanctuary: 'सुरक्षित स्थान',
  saved_sanctuary_header: 'सुरक्षित स्थान',
  saved_sanctuary_sub: 'महत्वपूर्ण गाइड और संसाधनों का आपका क्यूरेटेड संग्रह।',
  welcome_home: 'घर में स्वागत है दोस्त',
  unified_sanctuary: 'एकीकृत देखभाल अभयारण्य',
  comfort_recovery_desc: 'आपके आराम और रिकवरी के लिए आसान उपकरण',
  clinical_logic_desc: 'क्लीनिकल तर्क और भावनात्मक लचीलेपन के लिए एक कोमल अभयारण्य।',
  gen_brief: 'डॉक्टर ब्रीफ बनाएं',
  search_placeholder: 'खोजें...',
  select_perspective: 'अपना दृष्टिकोण चुनें',
  select_desc: 'अपनी यात्रा चुनें ताकि हम बच्चों के लिए जादू की कहानियों से लेकर रोगियों के लिए क्लीनिकल सहायता तक हर तरह की सहायता को व्यक्तिगत बना सकें।',
  role_patient: 'मरीज',
  role_caregiver: 'देखभाल करने वाला',
  role_hero: 'हीरो बच्चा',
  role_donor: 'समर्थक',
  role_survivor: 'सर्वाइवर',
  role_patient_desc: 'क्लीनिकल नेविगेशन, नर्सिंग सहायता, आसान गाइड और AI साथी',
  role_caregiver_desc: 'अभिभावकों और परिवार की सहायता के लिए पूर्ण संसाधन केंद्र',
  role_hero_desc: 'बडी हीरो साथी के साथ एक जादुई खोज',
  role_donor_desc: 'सामाजिक प्रभाव देखें और देखभाल नेविगेशन का समर्थन करें। कोई शुल्क नहीं।',
  role_survivor_desc: 'फॉलो-अप मॉनिटरिंग, स्कैन चिंता सहायता और कैंसर के बाद जीवन के गाइड',
  news_tab: 'समाचार',
  guides_tab: 'गाइड',
  portals_tab: 'पोर्टल',
  back: 'पीछे',
  continue: 'जारी रखें',
  save: 'सहेजें',
  add: 'जोड़ें',
  delete: 'हटाएं',
  logout: 'लॉगआउट',
  sync: 'सिंक',
  hero_quests: 'सुपर क्वेस्ट',
  daily_missions: 'XP के लिए मिशन पूरा करें',
  buddy_chat: 'बडी से बात करें',
  buddy_desc: 'आपका जादुई AI दोस्त',
  magic_studio: 'मैजिक स्टूडियो',
  magic_desc: 'अपने सपनों को रंग दें',
  hero_cinema: 'हीरो सिनेमा',
  cinema_choice: 'देखें और सीखें',
  stay_brave: 'बहादुर बनें',
  magic_energy: 'जादुई ऊर्जा',
  next_level: 'अगला स्तर',
  symptom_log: 'लक्षण लॉग',
  symptom_log_header: 'लक्षण लॉग',
  symptom_log_sub: 'अपनी ऑन्कोलॉजी टीम के साथ साझा करने के लिए शारीरिक परिवर्तनों को ट्रैक करें।',
  track_physical: 'शारीरिक रुझान ट्रैक करें',
  daily_sanctuary_focus: 'दैनिक अभयारण्य फोकस',
  hero_welcome: 'हीरो मुख्यालय में स्वागत है!',
  hero_level: 'हीरो स्तर',
  xp_to_go: 'अगले स्तर के लिए XP',
  open_studio: 'स्टूडियो खोलें',
  watch_movie: 'मूवी देखें',
  start_quest: 'क्वेस्ट शुरू करें',
  sticker_vault: 'स्टिकर वॉल्ट',
  commander_hub: 'कमांडर हब',
  collected: 'एकत्रित',
  locked: 'बंद',
  tap_to_open: 'खोलने के लिए टैप करें',
  unlocked: 'खुल गया',
  mark_complete: 'पूरा चिह्नित करें',
  completed: 'पूरा हुआ',
  magic_fact: 'जादुई तथ्य',
  mystery_box: 'मिस्ट्री बॉक्स',
  mystery_box_title: 'मिस्ट्री बॉक्स!',
  mystery_box_desc: 'अंदर एक विशेष हीरो खजाना छिपा है। देखना चाहते हैं?',
  new_sticker: 'नया स्टिकर!',
  bravery_sparkle: 'आपकी बहादुरी में एक नई चमक आ गई है!',
  level_up: 'लेवल अप!',
  reached_level: 'स्तर पर पहुँच गए',
  continue_quest: 'क्वेस्ट जारी रखें',
  memory_quest: 'स्मृति खोज',
  train_brain: 'दिमाग को ट्रेन करें',
  later: 'बाद में',
  open_now: 'अभी खोलें',
  xp_awarded: 'XP मिला',
  magic_energy_needed: 'अगले पावर-अप के लिए XP',
  hero_quest_banner: 'हीरो क्वेस्ट',
  cinema_banner: 'आपकी रिकवरी मिशन के लिए जादुई पल और बहादुरी की कहानियाँ।',
  scan_history: 'स्कैन इतिहास',
  read_analysis: 'विश्लेषण पढ़ें',
  add_reminder: 'रिमाइंडर जोड़ें',
  dismiss: 'हटाएं',
  analyzing: 'दवा का विश्लेषण हो रहा है...',
  vision_logic: 'जेमिनी प्रो विज़न लॉजिक',
  analyze_symptoms: 'पैटर्न विश्लेषण',
  generating_insights: 'रुझान ढूँढना...',
  symptom_patterns_header: 'लक्षण इंटेलिजेंस',
  symptom_patterns_sub: 'डॉक्टर से चर्चा के लिए अपने लॉग में क्लीनिकल पैटर्न खोजें।',
  'vid-io2_title': 'इनसाइड आउट 2 - बहादुर रहें',
  'vid-io2_desc': 'नई भावनाओं को समझने और कठिन परिवर्तनों के माध्यम से बहादुर बने रहने की एक जादुई यात्रा।',
  'vid-dino_title': 'द गुड डायनासोर',
  'vid-dino_desc': 'आर्लो सीखता है कि बहादुरी का अर्थ डर के बावजूद कदम उठाना है।',
  'vid-scarlett_title': 'स्कारलेट',
  'vid-scarlett_desc': 'साहस और नृत्य के माध्यम से अपनी जादुई दुनिया को फिर से खोजने वाली एक बहादुर लड़की की कहानी।',
  'vid-piper_title': 'पाइपर',
  'vid-piper_desc': 'एक छोटा नायक बड़ी लहरों पर विजय प्राप्त कर सबसे छोटी चीजों में कुछ अद्भुत ढूंढता है।'
};

// Telugu Strings
const TE_STRINGS = {
  dashboard: 'డ్యాష్‌బోర్డ్',
  mood_board: 'మూడ్ బోర్డ్',
  navigator: 'నేవిగేటర్',
  navigator_header: 'విజనరీ కేర్ నేవిగేటర్',
  navigator_sub: 'సంస్థాగత ప్రోటోకాల్స్ మరియు నిజ-సమయ వనరుల గ్రౌండింగ్‌తో ఖచ్చితంగా మ్యాప్ చేయబడిన క్లినికల్ రోడ్‌మ్యాప్స్.',
  med_scanner: 'మెడిసిన్ స్కానర్',
  meds_scanner_header: 'విజన్-AI మెడ్ స్కానర్',
  meds_scanner_sub: 'ఔషధాల రసాయన సమ్మేళనాలు, భద్రతా హెచ్చరికలు మరియు క్లినికల్ సూచనల యొక్క ఖచ్చితమైన విశ్లేషణ.',
  doc_intel: 'డాక్ ఇంటెల్',
  doc_intel_header: 'డాక్ ఇంటెల్ వాల్ట్',
  doc_intel_sub: 'రిపోర్టులను సురక్షితంగా సేవ్ చేయండి మరియు AI సందర్భాన్ని వివరించనివ్వండి',
  insights: 'జ్ఞాన కేంద్రం',
  insights_header: 'జ్ఞాన కేంద్రం',
  insights_sub: 'క్లినికల్ వార్తలు, ధృవీకరించబడిన పోర్టల్స్ మరియు నిపుణుల మార్గదర్శకాలు',
  meetups: 'సర్వైవర్ మీటప్స్',
  trust: 'నమ్మకం',
  hero_hub: 'హీరో హెడ్ క్వార్టర్స్',
  hero_garden: 'హీరో గార్డెన్',
  hero_tasks: 'పవర్ టాస్క్లు',
  emergency_sos: 'అత్యవసర SOS',
  impact_hub: 'ప్రభావ కేంద్రం',
  impact_hub_header: 'ప్రభావ కేంద్రం',
  impact_hub_sub: 'సామాజిక ప్రభావాన్ని చూడండి మరియు సంరక్షణ నావిగేషన్‌కు మద్దతు ఇవ్వండి',
  welcome: 'స్వాగతం',
  give_aid: 'సహాయం అందించండి',
  nursing_aid: 'నర్సింగ్ సహాయం',
  settings: 'సెట్టింగులు',
  companion: 'AI తోడు',
  finder: 'వెతకండి',
  finder_header: 'వనరుల అన్వేషకుడు',
  finder_sub: 'క్యాన్సర్ వనరులు మరియు సమీపంలోని ఫార్మసీలను కనుగొండి',
  schemes: 'సహాయ పథకాలు',
  schemes_header: 'సహాయ పథకాలు',
  schemes_sub: 'ప్రభుత్వ వ్రాతపనిని సులభంగా నావిగేట్ చేయండి. ధృవీకరించబడిన ఆర్థిక సహాయం.',
  survivors_hub: 'సర్వైవర్స్ హబ్',
  survivors_hub_header: 'సర్వైవర్స్ హబ్',
  survivors_hub_sub: 'క్యాన్సర్ తర్వాత జీవితం కోసం మీ ధైర్య నిలయం.',
  skills_hub: 'నైపుణ్య కేంద్రం',
  skills_hub_header: 'క్లినికల్ స్కిల్స్ హబ్',
  skills_hub_sub: 'AI-ఆధారిత ట్యుటోరియల్స్‌తో ఇంటి సంరక్షణ పనులను నేర్చుకోండి.',
  saved_sanctuary: 'సేవ్ చేసిన వనరులు',
  saved_sanctuary_header: 'భద్రపరచిన నిలయం',
  saved_sanctuary_sub: 'ముఖ్యమైన గైడ్‌లు మరియు వనరుల మీ సేకరణ.',
  welcome_home: 'ఇంటికి స్వాగతం మిత్రమా',
  unified_sanctuary: 'ఏకీకృత సంరక్షణ నిలయం',
  comfort_recovery_desc: 'మీ సౌకర్యం మరియు కోలుకోవడం కోసం సులభమైన సాధనాలు',
  clinical_logic_desc: 'క్లినికల్ తర్కం మరియు భావోద్వేగ స్థితిస్థాపకత కోసం ఒక సున్నితమైన నిలయం.',
  gen_brief: 'డాక్టర్ బ్రీఫ్ తయారు చేయండి',
  search_placeholder: 'వెతకండి...',
  select_perspective: 'మీ దృక్పథాన్ని ఎంచుకోండి',
  select_desc: 'పిల్లల కోసం మాయా కథల నుండి రోగులకు క్లినికల్ సహాయం వరకు ప్రతి మద్దతును మేము వ్యక్తిగతీకరించేలా మీ ప్రయాణాన్ని ఎంచుకోండి.',
  role_patient: 'రోగి',
  role_caregiver: 'సంరక్షకుడు',
  role_hero: 'హీరో పిల్లాడు',
  role_donor: 'మద్దతుదారు',
  role_survivor: 'సర్వైవర్',
  role_patient_desc: 'క్లినికల్ నావిగేషన్, నర్సింగ్ సహాయం, సులభమైన గైడ్‌లు మరియు AI తోడు',
  role_caregiver_desc: 'సంరక్షకులు మరియు కుటుంబ మద్దతు కోసం పూర్తి వనరుల కేంద్రం',
  role_hero_desc: 'బడ్డీ హీరో తోడుతో ఒక గేమిఫైడ్ మ్యాజిక్ క్వెస్ట్',
  role_donor_desc: 'సామాజిక ప్రభావాన్ని చూడండి మరియు సంరక్షణ నావిగేషన్‌కు మద్దతు ఇవ్వండి. ఫీజులు లేవు, స్వచ్ఛమైన ప్రభావం.',
  role_survivor_desc: 'ఫాలో-అప్ మానిటరింగ్, స్కాన్ ఆందోళన మద్దతు మరియు క్యాన్సర్ తర్వాత జీవితం గైడ్‌లు',
  news_tab: 'వార్తలు',
  guides_tab: 'గైడ్లు',
  portals_tab: 'పోర్టల్స్',
  back: 'వెనక్కి',
  continue: 'కొనసాగించు',
  save: 'సేవ్ చేయి',
  add: 'జత చేయి',
  delete: 'తొలగించు',
  logout: 'లాగ్ అవుట్',
  sync: 'సింక్ చేయి',
  hero_quests: 'సూపర్ క్వెస్ట్‌లు',
  daily_missions: 'XP కోసం మిషన్లు పూర్తి చేయండి',
  buddy_chat: 'బడ్డీతో మాట్లాడండి',
  buddy_desc: 'మీ మాయా AI స్నేహితుడు',
  magic_studio: 'మ్యాజిక్ స్టూడియో',
  magic_desc: 'మీ కలలకు రంగులు వేయండి',
  hero_cinema: 'హీరో సినిమా',
  cinema_choice: 'చూడండి & నేర్చుకోండి',
  stay_brave: 'ధైర్యంగా ఉండండి',
  magic_energy: 'మాయా శక్తి',
  next_level: 'తదుపరి స్థాయి',
  symptom_log: 'లక్షణాల లాగ్',
  symptom_log_header: 'లక్షణాల లాగ్',
  symptom_log_sub: 'మీ ఆంకాలజీ బృందంతో పంచుకోవడానికి శారీరక మార్పులను ట్రాక్ చేయండి.',
  track_physical: 'శారీరక ధోరణులను ట్రాక్ చేయండి',
  daily_sanctuary_focus: 'రోజువారీ నిలయ దృష్టి',
  hero_welcome: 'హీరో HQ కి స్వాగతం!',
  hero_level: 'హీరో స్థాయి',
  xp_to_go: 'తదుపరి స్థాయికి XP',
  open_studio: 'స్టూడియో తెరవండి',
  watch_movie: 'సినిమా చూడండి',
  start_quest: 'క్వెస్ట్ ప్రారంభించండి',
  sticker_vault: 'స్టిక్కర్ వాల్ట్',
  commander_hub: 'కమాండర్ హబ్',
  collected: 'సేకరించబడ్డాయి',
  locked: 'లాక్ చేయబడింది',
  tap_to_open: 'తెరవడానికి నొక్కండి',
  unlocked: 'అన్‌లాక్ చేయబడింది',
  mark_complete: 'పూర్తయినట్లు గుర్తించండి',
  completed: 'పూర్తయింది',
  magic_fact: 'మాయా నిజం',
  mystery_box: 'మిస్టరీ బాక్స్',
  mystery_box_title: 'మిస్టరీ బాక్స్!',
  mystery_box_desc: 'లోపल ఒక ప్రత్యేక హీరో నిధి దాగి ఉంది. చూడాలనుకుంటున్నారా?',
  new_sticker: 'కొత్త స్టిక్కర్!',
  bravery_sparkle: 'మీ ధైర్యానికి ఒక కొత్త మెరుపు వచ్చింది!',
  level_up: 'లెవల్ అప్!',
  reached_level: 'స్థాయికి చేరుకున్నారు',
  continue_quest: 'క్వెస్ట్ కొనసాగించండి',
  memory_quest: 'మెమరీ క్వెస్ట్',
  train_brain: 'మీ మెదడుకు శిక్షణ ఇవ్వండి',
  later: 'తర్వాత',
  open_now: 'ఇప్పుడే తెరువు',
  xp_awarded: 'XP అందించబడింది',
  magic_energy_needed: 'తదుపరి పवर-అప్ కోసం XP',
  hero_quest_banner: 'హీరో క్వెస్ట్',
  cinema_banner: 'మీ కోలుకునే మిషన్ కోసం మాయా క్షణాలు మరియు ధైర్యవంతమైన కథలు.',
  scan_history: 'スキャン చరిత్ర',
  read_analysis: 'విశ్లేషణ వినండి',
  add_reminder: 'రిమైండర్ జత చేయి',
  dismiss: 'తీసివేయి',
  analyzing: 'మందును విశ్లేషిస్తోంది...',
  vision_logic: 'జెమిని ప్రో విజన్ లాజిక్',
  analyze_symptoms: 'నమూనాలను విశ్లేషించండి',
  generating_insights: 'ధోరణులను కనుగొంటోంది...',
  symptom_patterns_header: 'లక్షణాల మేధస్సు',
  symptom_patterns_sub: 'మీ డాక్టర్‌తో చర్చించడానికి మీ లాగ్‌లో క్లినికల్ నమూనాలను కనుగొనండి.',
  'vid-io2_title': 'ఇన్‌సైడ్ అవుట్ 2 - ధైర్యంగా ఉండండి',
  'vid-io2_desc': 'కొత్త భావోద్వేగాలను అర్థం చేసుకోవడం మరియు కష్టమైన మార్పుల ద్వారా ధైర్యంగా ఉండటం గురించి ఒక మాయా ప్రयाణం.',
  'vid-dino_title': 'ది గుడ్ డైనోసార్',
  'vid-dino_desc': 'మీకు భయంగా అనిపించినా అడుగులు వేయడమే ధైర్యం అని ఆర్లో నేర్చుకుంటాడు.',
  'vid-scarlett_title': 'స్కార్లెట్',
  'vid-scarlett_desc': 'ధైర్యం మరియు నృత్యం ద్వారా తన మ్యాజిక్‌ను మళ్ళీ కనుగొన్న ఒక ధైర్యవంతురాలైన అమ్మాయి కథ.',
  'vid-piper_title': 'పైపర్',
  'vid-piper_desc': 'అతి చిన్న విషయాలలో కూడా అద్భుతమైనదాన్ని కనుగొనడానికి ఒక చిన్న హీరో పెద్ద అలలపై విజయం సాధిస్తాడు.'
};

// Map Languages to translation objects
export const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  [AppLanguage.ENGLISH]: EN_STRINGS,
  [AppLanguage.HINDI]: HI_STRINGS,
  [AppLanguage.URDU]: EN_STRINGS, // Placeholder
  [AppLanguage.TELUGU]: TE_STRINGS
};

export const SCHEMES: Scheme[] = [
  {
    id: 'ayushman-bharat',
    name: 'Ayushman Bharat (PM-JAY)',
    description: "The world's largest health insurance scheme providing ₹5 Lakh per family per year for secondary and tertiary care hospitalization.",
    eligibility: ['Households listed in SECC 2011 data', 'Low-income families across India', 'Verification via PMJAY portal'],
    documents: ['Ayushman Card / PM Letter', 'Aadhaar Card', 'Ration Card'],
    steps: ['Check eligibility on PMJAY portal', 'Visit empanelled hospital (JNMCH)', 'Verify biometric at Ayushman Mitra desk'],
    officialUrl: 'https://pmjay.gov.in/',
    type: 'GOVERNMENT',
    fundType: 'AYUSHMAN'
  },
  {
    id: 'alig-care-fund',
    name: 'Alig Care Foundation (Private Aid)',
    description: 'Local community-driven fund providing supplementary financial aid for diagnostic tests and medicines not covered by government schemes for JNMCH patients.',
    eligibility: ['Patients treated at JNMCH, Aligarh', 'Documented financial distress', 'Medical recommendation from Oncology dept'],
    documents: ['JNMCH OPD/IPD card', 'Income certificate / BPL card', 'Verified prescription/estimates'],
    steps: ['Consult Alig Care coordinator at JNMCH', 'Submit verified treatment estimates', 'Direct invoice settlement with pharmacy'],
    officialUrl: 'https://www.aligscare.org/',
    type: 'INSTITUTIONAL',
    fundType: 'ALIG_CARE'
  },
  {
    id: 'pm-relief-fund',
    name: 'PM Relief Fund',
    description: "The Prime Minister's National Relief Fund (PMNRF) provides immediate financial relief for specialized oncology treatments and life-saving procedures.",
    eligibility: ['Indian citizens in medical distress', 'Low-income households', 'Verification by clinical social work'],
    documents: ['Aadhaar Card', 'Income Certificate', 'Hospital Treatment Estimate'],
    steps: ['Apply through official portal', 'Verification by PMO', 'Direct hospital credit'],
    officialUrl: 'https://pmnrf.gov.in/',
    type: 'GOVERNMENT',
    fundType: 'PM_CARE'
  },
  {
    id: 'cm-relief-fund-up',
    name: 'CM Relief Fund',
    description: 'State-level assistance for residents of Uttar Pradesh facing high medical costs for critical cancer treatments at empanelled institutions like JNMCH.',
    eligibility: ['UP Domicile holders', 'Family income below threshold'],
    documents: ['Domicile Proof', 'Income Certificate', 'Estimate from JNMCH'],
    steps: ['Apply via Jansunwai portal', 'DM Office verification', 'Hospital settlement'],
    officialUrl: 'http://cmrf.up.nic.in/',
    type: 'GOVERNMENT',
    fundType: 'CM_CARE'
  }
];

export const CHILD_VIDEOS: ChildVideo[] = [
  {
    id: 'vid-io2',
    title: 'Inside Out 2 - Stay Brave',
    description: 'A magical journey into understanding new emotions and staying brave through difficult changes.',
    youtubeId: 'bPgiiPCZt60',
    videoUrl: '',
    externalUrl: 'https://youtu.be/bPgiiPCZt60',
    thumbnail: 'https://img.youtube.com/vi/bPgiiPCZt60/maxresdefault.jpg',
    category: 'Discovery'
  },
  {
    id: 'vid-dino',
    title: 'The Good Dinosaur',
    description: 'Arlo learns that bravery is taking steps even when you are scared of the unknown.',
    youtubeId: 'DWYeStSYZwk',
    videoUrl: '',
    externalUrl: 'https://youtu.be/DWYeStSYZwk',
    thumbnail: 'https://img.youtube.com/vi/DWYeStSYZwk/maxresdefault.jpg',
    category: 'Journey'
  },
  {
    id: 'vid-scarlett',
    title: 'Scarlett',
    description: 'A beautiful story about a brave girl finding her magic again through courage and dance.',
    youtubeId: 'heE_lieGsZ8',
    videoUrl: '',
    externalUrl: 'https://youtu.be/heE_lieGsZ8',
    thumbnail: 'https://img.youtube.com/vi/heE_lieGsZ8/maxresdefault.jpg',
    category: 'Inner Power'
  }
];

export const TRUSTED_RESOURCES = [
  {
    id: 'res-jnmch-portal',
    title: 'JNMCH Oncology Portal',
    url: 'https://www.amu.ac.in/colleges/j-n-medical-college',
    description: 'Official clinical protocols and department resources for J.N. Medical College & Hospital, Aligarh.',
    category: 'Regional',
    tag: 'Hospital'
  },
  {
    id: 'res-tmc',
    title: 'Tata Memorial Centre (TMC)',
    url: 'https://tmc.gov.in/index.php/en/',
    description: 'India’s premier cancer research and treatment centre. Access to official guidelines and patient resources.',
    category: 'Institutional',
    tag: 'National'
  },
  {
    id: 'res-aiims-delhi',
    title: 'AIIMS New Delhi (Oncology)',
    url: 'https://www.aiims.edu/',
    description: 'The National Cancer Institute (NCI) AIIMS Jhajjar and main campus oncology clinical services.',
    category: 'Institutional',
    tag: 'Premier'
  },
  {
    id: 'res-rgci',
    title: 'Rajiv Gandhi Cancer Institute',
    url: 'https://www.rgcirc.org/',
    description: 'Comprehensive cancer care and research center in India offering specialized patient information.',
    category: 'Clinical',
    tag: 'Research'
  },
  {
    id: 'res-cansupport',
    title: 'CanSupport India',
    url: 'https://cansupport.org/',
    description: 'Pioneering home-based palliative care services and support for cancer patients in North India.',
    category: 'Support',
    tag: 'Palliative'
  },
  {
    id: 'res-nci-global',
    title: 'National Cancer Institute (NCI)',
    url: 'https://www.cancer.gov/',
    description: 'The U.S. federal government\'s principal agency for cancer research and training.',
    category: 'Global',
    tag: 'Authority'
  },
  {
    id: 'res-nhs-cancer',
    title: 'NHS UK Cancer Hub',
    url: 'https://www.nhs.uk/conditions/cancer/',
    description: 'Public health information about cancer types, diagnosis, and treatment pathways.',
    category: 'Policy',
    tag: 'Public Health'
  },
  {
    id: 'res-who-obs',
    title: 'WHO Global Cancer Observatory',
    url: 'https://gco.iarc.fr/',
    description: 'International data and statistics on cancer burden and clinical research summaries globally.',
    category: 'Research',
    tag: 'Global'
  },
  {
    id: 'res-cancercare-groups',
    title: 'CancerCare Support Groups',
    url: 'https://www.cancercare.org/support_groups/',
    description: 'Connect with a community of survivors and experts for emotional support and guidance.',
    category: 'Community',
    tag: 'Verified'
  },
  {
    id: 'res-alig',
    title: 'Alig Care Foundation',
    url: 'https://www.aligscare.org/',
    description: 'Community-led oncology support and care navigation in the Aligarh region.',
    category: 'Regional',
    tag: 'Community'
  }
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp-1',
    title: 'Support for Sarcoma Treatment',
    patientName: 'Sameer K.',
    targetAmount: 500000,
    raisedAmount: 320000,
    category: 'MEDICAL',
    story: 'Sameer is a brave 12-year-old fighting osteosarcoma. His family needs help covering the costs of specialized chemotherapy.',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=800',
    donationsCount: 142
  }
];

export const VERIFIED_GUIDES: Article[] = [
  {
    id: 'guide-1',
    title: 'Managing Chemotherapy Side Effects',
    summary: 'A comprehensive guide on handling nausea, fatigue, and other common side effects at home.',
    content: 'Detailed strategies for managing physical and emotional changes during clinical treatment cycles.',
    category: 'LIFESTYLE',
    imageUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&q=80&w=800',
    tags: ['Chemo', 'Side Effects', 'Home Care'],
    link: 'https://www.cancer.gov/about-cancer/treatment/side-effects'
  },
  {
    id: 'guide-palliative',
    title: 'Understanding Palliative Care',
    summary: 'Learn how palliative care focuses on relief from symptoms and stress during treatment.',
    content: 'Palliative care is not just for end-of-life; it is specialized medical care for anyone with a serious illness.',
    category: 'SYMPTOMS',
    imageUrl: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?auto=format&fit=crop&q=80&w=800',
    tags: ['Comfort', 'Support', 'Quality of Life'],
    link: 'https://www.who.int/news-room/fact-sheets/detail/palliative-care'
  },
  {
    id: 'guide-finance',
    title: 'Financial Aid Roadmap',
    summary: 'Navigating hospital billing, Ayushman Bharat, and private foundation grants in India.',
    content: 'Step-by-step instructions on securing funding for critical cancer treatment cycles.',
    category: 'SCHEMES',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-1696413565d3?auto=format&fit=crop&q=80&w=800',
    tags: ['Grants', 'Ayushman', 'Hospital Billing'],
    link: 'https://pmjay.gov.in/'
  },
  {
    id: 'guide-surgery',
    title: 'Post-Surgery Healing',
    summary: 'A guide to physical recovery, wound care, and gentle movement after oncology surgery.',
    content: 'How to monitor incisions and when to alert your surgical team about changes.',
    category: 'LIFESTYLE',
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=800',
    tags: ['Surgery', 'Wound Care', 'Recovery'],
    link: 'https://www.cancer.org/treatment/treatments-and-side-effects/surgery.html'
  },
  {
    id: 'guide-cognitive',
    title: 'Managing Chemobrain',
    summary: 'Strategies to cope with memory loss and lack of focus during and after chemotherapy.',
    content: 'Cognitive tools and lifestyle adjustments to improve mental clarity during treatment.',
    category: 'EMOTIONAL',
    imageUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?auto=format&fit=crop&q=80&w=800',
    tags: ['Memory', 'Focus', 'Brain Fog'],
    link: 'https://www.cancer.gov/about-cancer/treatment/side-effects/memory-attention-problems'
  },
  {
    id: 'guide-selfcare',
    title: 'Caregiver Resilience',
    summary: 'Avoiding burnout while supporting a loved one through their oncology journey.',
    content: 'Practical mental health tips and community support links for primary caregivers.',
    category: 'EMOTIONAL',
    imageUrl: 'https://images.unsplash.com/photo-1484820540004-14229fe36ca4?auto=format&fit=crop&q=80&w=800',
    tags: ['Caregiver', 'Mental Health', 'Resilience'],
    link: 'https://www.cancercare.org/tagged/caregiving'
  },
  {
    id: 'guide-trials',
    title: 'Clinical Trials 101',
    summary: 'How to search for and understand the benefits of joining a clinical research study.',
    content: 'An objective guide to the phases of clinical trials and patient safety protocols.',
    category: 'SYMPTOMS',
    imageUrl: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&q=80&w=800',
    tags: ['Research', 'Trials', 'Innovation'],
    link: 'https://www.clinicaltrials.gov/'
  },
  {
    id: 'guide-genetics',
    title: 'The Role of Genetics',
    summary: 'Understanding how genetic testing helps oncologist tailor precision medicine for your specific cancer subtype.',
    content: 'Explanation of biomarkers, mutations, and how targeted therapy works at a molecular level.',
    category: 'SYMPTOMS',
    imageUrl: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?auto=format&fit=crop&q=80&w=800',
    tags: ['Genetics', 'Subtype', 'Biomarkers'],
    link: 'https://www.cancer.gov/about-cancer/causes-prevention/genetics'
  }
];