import { Scheme, Campaign, Article, SupportGroup, ChildVideo, AppEvent, AppLanguage } from './types';

const EN_STRINGS = {
  dashboard: 'Dashboard',
  mood_board: 'Mood Board',
  navigator: 'Navigator',
  navigator_header: 'Visionary Care Navigator',
  navigator_sub: 'Precision-mapped clinical roadmaps integrated with institutional protocols.',
  med_scanner: 'Meds Scanner',
  meds_scanner_header: 'Vision AI-MedScanner',
  meds_scanner_sub: 'Medicine Recognition, Drug Details, Dosage Insights, and Safety Guidance.',
  doc_intel: 'Doc Intel',
  doc_intel_header: 'Doc Intel Vault',
  doc_intel_sub: 'Securely store reports in Azure Vault and let AI explain context.',
  insights: 'Insights Hub',
  insights_header: 'Insights Hub',
  insights_sub: 'Clinical news verified portals and expert guides.',
  meetups: 'Survivor Meetups',
  trust: 'Trust',
  hero_hub: 'Hero HQ',
  hero_garden: 'Hero Garden',
  hero_tasks: 'Power Tasks',
  emergency_sos: 'EMERGENCY SOS',
  emergency_prep: 'Crisis Guard',
  emergency_header: 'Crisis Readiness Guard',
  emergency_sub: 'Critical protocols and identification checklists for oncology emergencies.',
  impact_hub: 'Impact Hub',
  impact_hub_header: 'Impact Hub',
  impact_hub_sub: 'Witness social impact and support care navigation.',
  welcome: 'Welcome',
  give_aid: 'Support Impact',
  nursing_aid: 'Nursing Aid',
  settings: 'Settings',
  companion: 'AI Companion',
  finder: 'Finder',
  finder_header: 'Resource Finder',
  finder_sub: 'Locate oncology resources and nearby pharmacies.',
  schemes: 'Aid Schemes',
  schemes_header: 'Aid Schemes',
  schemes_sub: 'Navigate government paperwork with ease. Verified financial aid.',
  survivors_hub: 'Survivors Hub',
  survivors_hub_header: 'Survivors Hub',
  survivors_hub_sub: 'Your Resilience Sanctuary for life after cancer.',
  skills_hub: 'Skills Hub',
  skills_hub_header: 'Clinical Skills Hub',
  skills_hub_sub: 'Master home-care tasks with AI-guided tutorials.',
  saved_sanctuary: 'Saved Sanctuary',
  saved_sanctuary_header: 'Saved Sanctuary',
  saved_sanctuary_sub: 'Your curated collection of important guides and resources.',
  welcome_home: 'Welcome Home Friend',
  unified_sanctuary: 'Unified Care Sanctuary',
  comfort_recovery_desc: 'Easy to use tools for your comfort and recovery.',
  clinical_logic_desc: 'A gentle sanctuary for clinical, logical, and emotional resilience.\nProviding precision-mapped navigation and institutional aid guidance.\nCompassionate AI support ensuring no one fights this battle alone.',
  gen_brief: 'Generate Doctor Brief',
  search_placeholder: 'Search Sanctuary...',
  select_perspective: 'Select your Perspective',
  select_desc: 'Choose your journey so we can personalize every bit of support.',
  role_patient: 'Patient',
  role_caregiver: 'Caregiver',
  role_hero: 'Hero Kid',
  role_donor: 'Supporter',
  role_survivor: 'Survivor',
  role_patient_desc: 'Clinical navigation, nursing aid, and easy read guides.',
  role_caregiver_desc: 'Full resource hub for guardians and family support.',
  role_hero_desc: 'A gamified magic quest with Buddy the hero companion.',
  role_donor_desc: 'Witness social impact and support care navigation.',
  role_survivor_desc: 'Follow up monitoring and life after cancer guides.',
  news_tab: 'News',
  guides_tab: 'Guides',
  portals_tab: 'Portals',
  back: 'Back',
  continue: 'Continue',
  save: 'Save',
  add: 'Add',
  delete: 'Delete',
  logout: 'Logout',
  sync: 'Sync',
  buddy_chat: 'Talk to Buddy',
  buddy_desc: 'Your magic AI friend',
  hero_quests: 'Super Quests',
  hero_quest_banner: 'The Hero Quest',
  hero_welcome: 'Welcome to Hero HQ!',
  hero_level: 'Hero Level',
  magic_energy_needed: 'XP to Next Power-up',
  memory_quest: 'Memory Quest',
  train_brain: 'Train Your Brain',
  magic_studio: 'Magic Studio',
  open_studio: 'Open Studio',
  mystery_box: 'Mystery Box',
  mystery_box_title: 'The Mystery Box!',
  mystery_box_desc: 'A special hero treasure is hidden inside. Want to see it?',
  tap_to_open: 'Tap to Open',
  unlocked: 'Unlocked',
  sticker_vault: 'Sticker Vault',
  collected: 'Collected',
  magic_fact: 'Magic Fact',
  hero_cinema: 'Hero Cinema',
  cinema_banner: 'Magic moments and brave stories for your recovery mission.',
  stay_brave: 'Stay Brave',
  magic_energy: 'Magic Energy',
  symptom_log: 'Symptom Log',
  symptom_log_header: 'Symptom Log',
  symptom_log_sub: 'Track physical changes to share with your oncology team.',
  scan_history: 'Scan History',
  add_reminder: 'Add Reminder',
  analyzing: 'Analyzing Medicine...',
  analyze_symptoms: 'Analyze Patterns',
  generating_insights: 'Finding Trends...',
  symptom_patterns_header: 'Symptom Intelligence',
  symptom_patterns_sub: 'Discover clinical patterns in your log.',
  daily_sanctuary_focus: 'Daily Sanctuary Focus',
  completed: 'Completed',
  mark_complete: 'Mark Complete',
  open_now: 'Open Now',
  later: 'Later',
  new_sticker: 'New Sticker!',
  bravery_sparkle: 'Your bravery just got a new sparkle!',
  xp_awarded: 'XP Awarded',
  level_up: 'Level Up!',
  reached_level: 'Reached Level',
  continue_quest: 'Continue Quest',
  transparency: 'Transparency',
  transparency_title: 'Trust & Ethics Center',
  transparency_desc: 'LifePal is built on a foundation of ethical AI, institutional trust, and community safety.',
  medical_guardrails: 'Medical Guardrails',
  no_diagnosis_title: 'No Diagnosis',
  no_diagnosis_desc: 'LifePal is an information companion. It cannot and will not tell you if you have a specific disease.',
  no_prescription_title: 'No Prescriptions',
  no_prescription_desc: 'The AI never suggests specific medication dosages. All changes must be approved by your oncologist.',
  amu_grounded_title: 'Institutional Grounding',
  amu_grounded_desc: 'All regional advice is grounded in the protocols of JNMCH, Aligarh.',
  ai_ethics_title: 'Intelligent Assistance',
  data_sovereignty_title: 'Data Sovereignty',
  financial_transparency_title: 'Direct Aid Flow',
  pediatric_sanctuary_title: 'Pediatric Sanctuary',
  // New Impact Hub Strings
  impact_patients_supported: 'Patients Supported',
  impact_care_interactions: 'Care Interactions',
  impact_mental_health: 'Mental Health Check-ins',
  impact_navigation: 'Navigation Sessions',
  impact_kindness_title: 'The Power of Your Kindness',
  impact_hero_ways: 'Ways to Be a Hero',
  impact_sponsor_title: 'Sponsor Treatment',
  impact_sponsor_desc: 'Many patients pause chemo due to lack of funds. Your donation buys specific vials of life-saving drugs.',
  impact_gift_life: 'Gift Life Flow',
  impact_gift_life_desc: 'Chemotherapy depletes platelets. One unit of your blood can save 3 different patients.',
  impact_share_warmth: 'Share Warmth',
  impact_share_warmth_desc: 'Winter is hard in the wards. Donate blankets or nutritional supplements.',
  impact_active_zones: 'Active Support Zones',
  impact_milestones: 'Your Milestones',
  // New Emergency Strings
  emergency_immediate_action: 'Immediate Action (First 5 Mins)',
  emergency_key_numbers: 'Key Numbers',
  emergency_red_folder: 'The "Red Folder" Checklist',
  emergency_prevention: 'Prevention Vigilance',
  // New Navigator Labels
  nav_clinical_id: 'Clinical Identifier (Cancer Type)',
  nav_location: 'Regional Context (Location)',
  nav_priority: 'Select Intelligence Priority',
  nav_launch: 'Launch Precision Navigator',
  nav_strategy: 'Generated Strategy',
  nav_institutional: 'Institutional Relief',
  nav_strategic_facilities: 'Strategic Facilities'
};

const HI_STRINGS = {
  dashboard: 'डैशबोर्ड',
  mood_board: 'मूड बोर्ड',
  navigator: 'नेविगेटर',
  navigator_header: 'केयर नेविगेटर',
  navigator_sub: 'संस्थागत प्रोटोकॉल के साथ सटीक क्लीनिकल रोडमैप।',
  med_scanner: 'दवा स्कैनर',
  meds_scanner_header: 'Vision AI-MedScanner',
  meds_scanner_sub: 'दवा की पहचान, खुराक अंतर्दृष्टि और सुरक्षा मार्गदर्शन।',
  doc_intel: 'डॉक इंटेल',
  doc_intel_header: 'डॉक इंटेल वॉल्ट',
  doc_intel_sub: 'रिपोर्ट सुरक्षित रूप से एज़्योर वॉल्ट में स्टोर करें।',
  insights: 'इनसाइट्स हब',
  insights_header: 'इनसाइट्स हब',
  insights_sub: 'सत्यापित समाचार और विशेषज्ञ गाइड।',
  meetups: 'सर्वाइवर मीटअप',
  trust: 'ट्रस्ट',
  hero_hub: 'हीरो मुख्यालय',
  hero_garden: 'हीरो गार्डन',
  hero_tasks: 'पावर टास्क',
  emergency_sos: 'आपातकालीन SOS',
  emergency_prep: 'क्राइसिस गार्ड',
  emergency_header: 'क्राइसिस गार्ड',
  emergency_sub: 'कैंसर आपात स्थितियों के लिए महत्वपूर्ण प्रोटोकॉल।',
  impact_hub: 'इम्पैक्ट हब',
  impact_hub_header: 'इम्पैक्ट हब',
  impact_hub_sub: 'सामाजिक प्रभाव देखें और मदद करें।',
  welcome: 'स्वागत है',
  give_aid: 'सहायता दें',
  nursing_aid: 'नर्सिंग सहायता',
  settings: 'सेटिंग्स',
  companion: 'एआई साथी',
  finder: 'खोजक',
  finder_header: 'संसाधन खोजक',
  finder_sub: 'नजदीकी फार्मेसी और कैंसर संसाधनों का पता लगाएं।',
  schemes: 'सहायता योजनाएं',
  schemes_header: 'सहायता योजनाएं',
  schemes_sub: 'सरकारी सहायता को आसानी से नेविगेट करें।',
  survivors_hub: 'सर्वाइवर्स हब',
  survivors_hub_header: 'सर्वाइवर्स हब',
  survivors_hub_sub: 'कैंसर के बाद जीवन के लिए आपका सुरक्षित स्थान।',
  skills_hub: 'कौशल हब',
  skills_hub_header: 'क्लीनिकल स्किल्स हब',
  skills_hub_sub: 'एआई ट्यूटोरियल के साथ घर पर देखभाल सीखें।',
  saved_sanctuary: 'सुरक्षित स्थान',
  saved_sanctuary_header: 'सुरक्षित स्थान',
  saved_sanctuary_sub: 'आपके द्वारा सहेजे गए महत्वपूर्ण गाइड और संसाधन।',
  welcome_home: 'घर में स्वागत है दोस्त',
  unified_sanctuary: 'एकीकृत केयर हब',
  comfort_recovery_desc: 'आपकी रिकवरी के लिए आसान टूल।',
  clinical_logic_desc: 'क्लीनिकल तर्क और भावनात्मक मजबूती के लिए एक कोमल स्थान।',
  gen_brief: 'डॉक्टर ब्रीफ बनाएं',
  search_placeholder: 'खोजें...',
  select_perspective: 'अपना दृष्टिकोण चुनें',
  select_desc: 'अपनी यात्रा चुनें ताकि हम आपकी सहायता कर सकें।',
  role_patient: 'मरीज',
  role_caregiver: 'देखभाल करने वाला',
  role_hero: 'हीरो बच्चा',
  role_donor: 'समर्थक',
  role_survivor: 'सर्वाइवर',
  role_patient_desc: 'क्लीनिकल नेविगेशन और आसान गाइड।',
  role_caregiver_desc: 'परिवार के लिए पूर्ण संसाधन हब।',
  role_hero_desc: 'बडी एआई साथी के साथ एक जादुई खोज।',
  role_donor_desc: 'सामाजिक प्रभाव देखें और देखभाल में मदद करें।',
  role_survivor_desc: 'कैंसर के बाद जीवन के लिए फॉलो-अप गाइड।',
  news_tab: 'समाचार',
  guides_tab: 'गाइड',
  portals_tab: 'पोर्टल',
  back: 'पीछे',
  continue: 'जारी रखें',
  save: 'सहेजें',
  add: 'जोड़ें',
  delete: 'हटाएं',
  logout: 'लॉगआउट',
  sync: 'सिंक',
  buddy_chat: 'बडी से बात करें',
  buddy_desc: 'आपका जादुई एआई दोस्त',
  hero_quests: 'सुपर क्वेस्ट',
  hero_quest_banner: 'हीरो क्वेस्ट',
  hero_welcome: 'हीरो मुख्यालय में आपका स्वागत है!',
  hero_level: 'हीरो स्तर',
  magic_energy_needed: 'अगले पावर-अप के लिए XP',
  memory_quest: 'मेमोरी क्वेस्ट',
  train_brain: 'दिमाग को ट्रेन करें',
  magic_studio: 'मैजिक स्टूडियो',
  open_studio: 'स्टूडियो खोलें',
  mystery_box: 'मिस्ट्री बॉक्स',
  mystery_box_title: 'मिस्ट्री बॉक्स!',
  mystery_box_desc: 'अंदर एक विशेष खजाना छिपा है। देखना चाहते हैं?',
  tap_to_open: 'खोलने के लिए टैप करें',
  unlocked: 'खुल गया',
  sticker_vault: 'स्टिकर वॉल्ट',
  collected: 'एकत्रित',
  magic_fact: 'जादुई तथ्य',
  hero_cinema: 'हीरो सिनेमा',
  cinema_banner: 'आपकी रिकवरी के लिए जादुई पल और कहानियाँ।',
  stay_brave: 'बहादुर रहें',
  magic_energy: 'जादुई ऊर्जा',
  symptom_log: 'लक्षण लॉग',
  symptom_log_header: 'लक्षण लॉग',
  symptom_log_sub: 'शारीरिक परिवर्तनों को ट्रैक करें।',
  scan_history: 'स्कैन इतिहास',
  add_reminder: 'रिमाइंडर जोड़ें',
  analyzing: 'दवा का विश्लेषण हो रहा है...',
  analyze_symptoms: 'पैटर्न विश्लेषण',
  generating_insights: 'रुझान ढूँढना...',
  symptom_patterns_header: 'लक्षण इंटेलिजेंस',
  symptom_patterns_sub: 'अपने लॉग में क्लीनिकल पैटर्न खोजें।',
  daily_sanctuary_focus: 'दैनिक फोकस',
  completed: 'पूरा हुआ',
  mark_complete: 'पूरा चिह्नित करें',
  open_now: 'अभी खोलें',
  later: 'बाद में',
  new_sticker: 'नया स्टिकर!',
  bravery_sparkle: 'आपकी बहादुरी में एक नई चमक आ गई है!',
  xp_awarded: 'XP मिला',
  level_up: 'लेवल अप!',
  reached_level: 'स्तर पर पहुँच गए',
  continue_quest: 'क्वेस्ट जारी रखें',
  transparency: 'पारदर्शिता',
  transparency_title: 'ट्रस्ट और एथिक्स सेंटर',
  transparency_desc: 'लाइफपाल नैतिक एआई, संस्थागत विश्वास और सामुदायिक सुरक्षा की नींव पर बना है।',
  medical_guardrails: 'चिकित्सा सुरक्षा सीमाएँ',
  no_diagnosis_title: 'कोई निदान नहीं',
  no_diagnosis_desc: 'लाइफपाल एक सूचना साथी है। यह आपको निदान नहीं देगा।',
  no_prescription_title: 'कोई नुस्खा नहीं',
  no_prescription_desc: 'एआई कभी भी विशिष्ट दवा की खुराक का सुझाव नहीं देता है।',
  amu_grounded_title: 'संस्थागत आधार',
  amu_grounded_desc: 'सभी क्षेत्रीय सलाह जेएनएमसीएच, अलीगढ़ के प्रोटोकॉल पर आधारित है।',
  ai_ethics_title: 'बुद्धिमान सहायता',
  data_sovereignty_title: 'डेटा संप्रभुता',
  financial_transparency_title: 'प्रत्यक्ष सहायता प्रवाह',
  pediatric_sanctuary_title: 'बाल चिकित्सा अभयारण्य',
  impact_patients_supported: 'मरीजों की सहायता की गई',
  impact_care_interactions: 'देखभाल बातचीत',
  impact_mental_health: 'मानसिक स्वास्थ्य चेक-इन',
  impact_navigation: 'नेविगेशन सत्र',
  impact_kindness_title: 'आपकी दयालुता की शक्ति',
  impact_hero_ways: 'हीरो बनने के तरीके',
  impact_sponsor_title: 'उपचार प्रायोजित करें',
  impact_sponsor_desc: 'कई मरीज धन की कमी के कारण कीमो रोक देते हैं। आपका दान दवा की विशिष्ट शीशियाँ खरीदता है।',
  impact_gift_life: 'जीवन प्रवाह का उपहार',
  impact_gift_life_desc: 'कीमोथेरेपी प्लेटलेट्स को कम करती है। आपके रक्त की एक यूनिट 3 मरीजों की जान बचा सकती है।',
  impact_share_warmth: 'गर्मी साझा करें',
  impact_share_warmth_desc: 'वार्डों में सर्दियाँ कठिन होती हैं। कंबल या पोषण संबंधी पूरक दान करें।',
  impact_active_zones: 'सक्रिय सहायता क्षेत्र',
  impact_milestones: 'आपके मील के पत्थर',
  emergency_immediate_action: 'तत्काल कार्रवाई (पहले 5 मिनट)',
  emergency_key_numbers: 'मुख्य नंबर',
  emergency_red_folder: '"लाल फ़ोल्डर" चेकलिस्ट',
  emergency_prevention: 'रोकथाम सतर्कता',
  nav_clinical_id: 'क्लीनिकल पहचानकर्ता (कैंसर प्रकार)',
  nav_location: 'क्षेत्रीय संदर्भ (स्थान)',
  nav_priority: 'इंटेलिजेंस प्राथमिकता चुनें',
  nav_launch: 'लॉन्च नेविगेटर',
  nav_strategy: 'तैयार रणनीति',
  nav_institutional: 'संस्थागत राहत',
  nav_strategic_facilities: 'रणनीतिक सुविधाएं'
};

const UR_STRINGS = {
  dashboard: 'ڈیش بورڈ',
  mood_board: 'موڈ بورڈ',
  navigator: 'نیویگیٹر',
  navigator_header: 'کیئر نیویگیٹر',
  navigator_sub: 'طبی روڈ میپ اور وسائل کی معلومات۔',
  med_scanner: 'میڈ اسکینر',
  meds_scanner_header: 'Vision AI-MedScanner',
  meds_scanner_sub: 'دوا کی پہچان، خوراک کی بصیرت، اور حفاظتی رہنمائی۔',
  doc_intel: 'دستاویز انٹیل',
  doc_intel_header: 'دستاویز انٹیل والٹ',
  doc_intel_sub: 'رپورٹس کو ایزیور والٹ میں محفوظ کریں۔',
  insights: 'بصیرت مرکز',
  insights_header: 'بصیرت مرکز',
  insights_sub: 'طبی خبریں اور ماہر گائیڈز۔',
  meetups: 'سروائیور ملاقاتیں',
  trust: 'بھروسہ',
  hero_hub: 'ہیرو ہیڈ کوارٹر',
  hero_garden: 'ہیرو گارڈن',
  hero_tasks: 'پاور ٹاسک',
  emergency_sos: 'ہنگامی SOS',
  emergency_prep: 'کرائسس گارڈ',
  emergency_header: 'کرائسس گارڈ',
  emergency_sub: 'کینسر کی ہنگامی صورتحال کے لیے پروٹوکول۔',
  impact_hub: 'اثر مرکز',
  impact_hub_header: 'اثر مرکز',
  impact_hub_sub: 'سماجی اثر دیکھیں اور مدد کریں۔',
  welcome: 'خوش آمدید',
  give_aid: 'مدد کریں',
  nursing_aid: 'نرسنگ مدد',
  settings: 'ترتیبات',
  companion: 'اے آئی ساتھی',
  finder: 'تلاش کار',
  finder_header: 'وسائل تلاش کریں',
  finder_sub: 'قریبی فارمیسی اور طبی مراکز تلاش کریں۔',
  schemes: 'امدادی اسکیمیں',
  schemes_header: 'امدادی اسکیمیں',
  schemes_sub: 'سرکاری مدد اور فنڈز کی معلومات۔',
  survivors_hub: 'سروائیورز مرکز',
  survivors_hub_header: 'سروائیورز مرکز',
  survivors_hub_sub: 'صحت یابی کے بعد کا سفر۔',
  skills_hub: 'ہنر مرکز',
  skills_hub_header: 'کلینیکل ہنر مرکز',
  skills_hub_sub: 'گھر پر دیکھ بھال کے طریقے سیکھیں۔',
  saved_sanctuary: 'محفوظ پناہ گاہ',
  saved_sanctuary_header: 'محفوظ پناہ گاہ',
  saved_sanctuary_sub: 'آپ کے محفوظ کردہ وسائل۔',
  welcome_home: 'خوش آمدید دوست',
  unified_sanctuary: 'یونیفائیڈ کیئر ہب',
  comfort_recovery_desc: 'صحت یابی کے لیے آسان ٹولز۔',
  clinical_logic_desc: 'طبی اور جذباتی مدد کے لیے ایک نرم جگہ۔',
  gen_brief: 'ڈاکٹر بریف تیار کریں',
  search_placeholder: 'تلاش کریں...',
  select_perspective: 'اپنا نقطہ نظر منتخب کریں',
  select_desc: 'اپنا سفر منتخب کریں تاکہ ہم مدد کر سکیں۔',
  role_patient: 'مریض',
  role_caregiver: 'نگہداشت کنندہ',
  role_hero: 'ہیرو بچہ',
  role_donor: 'معاون',
  role_survivor: 'سروائیور',
  role_patient_desc: 'طبی نیویگییشن اور آسان گائیڈز۔',
  role_caregiver_desc: 'خاندان کے لیے مکمل وسائل مرکز۔',
  role_hero_desc: 'بڈی اے آئی ساتھی کے ساتھ ایک جادوئی مشن۔',
  role_donor_desc: 'سماجی اثر دیکھیں اور مدد فراہم کریں۔',
  role_survivor_desc: 'صحت یابی کے بعد کی نگرانی۔',
  news_tab: 'خبریں',
  guides_tab: 'گائیڈز',
  portals_tab: 'پورٹلز',
  back: 'واپس',
  continue: 'جاری رکھیں',
  save: 'محفوظ کریں',
  add: 'شامل کریں',
  delete: 'حذف کریں',
  logout: 'لاگ آؤٹ',
  sync: 'مطابقت پذیری',
  buddy_chat: 'بڈی سے بات کریں',
  buddy_desc: 'آپ کا جادوئی اے آئی دوست',
  hero_quests: 'سپر کوئسٹس',
  hero_quest_banner: 'ہیرو مشن',
  hero_welcome: 'ہیرو ہیڈ کوارٹر میں خوش آمدید!',
  hero_level: 'ہیرو کی سطح',
  magic_energy_needed: 'ایکس پی درکار ہے',
  memory_quest: 'یادداشت کا مشن',
  train_brain: 'دماغ کو تربیت دیں',
  magic_studio: 'جادو اسٹوڈیو',
  open_studio: 'اسٹوڈیو کھولیں',
  mystery_box: 'پراسرار باکس',
  mystery_box_title: 'پراسرار باکس!',
  mystery_box_desc: 'اندر ایک خاص خزانہ چھپا ہے۔ دیکھنا چاہتے ہیں؟',
  tap_to_open: 'کھولنے کے لیے دبائیں',
  unlocked: 'کھول دیا گیا',
  sticker_vault: 'اسٹیکر والٹ',
  collected: 'جمع شدہ',
  magic_fact: 'جادوئی حقیقت',
  hero_cinema: 'ہیرو سنیما',
  cinema_banner: 'آپ کی صحت یابی کے مشن کے لیے جادوئی لمحات۔',
  stay_brave: 'ہیرو سنیما',
  magic_energy: 'جادوئی توانائی',
  symptom_log: 'علامات کا لاگ',
  symptom_log_header: 'علامات کا لاگ',
  symptom_log_sub: 'جسمانی تبدیلیوں کو ٹریک کریں۔',
  scan_history: 'اسکین کی تاریخ',
  add_reminder: 'یاد دہانی شامل کریں',
  analyzing: 'تجزیہ ہو رہا ہے...',
  analyze_symptoms: 'پیٹرن کا تجزیہ کریں',
  generating_insights: 'بصیرتیں تلاش کی جا رہی ہیں...',
  symptom_patterns_header: 'علامات کی ذہانت',
  symptom_patterns_sub: 'اپنے لاگ میں طبی پیٹرن دریافت کریں۔',
  daily_sanctuary_focus: 'روزانہ کی توجہ',
  completed: 'مکمل ہو گیا',
  mark_complete: 'مکمل نشان زد کریں',
  open_now: 'ابھی کھولیں',
  later: 'بعد میں',
  new_sticker: 'نیا اسٹیکر!',
  bravery_sparkle: 'آپ کی بہادری میں ایک نئی چمک آگئی ہے!',
  xp_awarded: 'XP مل گیا',
  level_up: 'لیول اپ!',
  reached_level: 'سطح پر پہنچ گئے',
  continue_quest: 'مشن جاری رکھیں',
  transparency: 'شفافیت',
  transparency_title: 'ٹرسٹ اور اخلاقیات کا مرکز',
  transparency_desc: 'لائف پال اخلاقی AI، ادارہ جاتی اعتماد اور کمیونٹی کی حفاظت کی بنیاد پر بنایا گیا ہے۔',
  medical_guardrails: 'طبی حفاظتی اقدامات',
  no_diagnosis_title: 'کوئی تشخیص نہیں',
  no_diagnosis_desc: 'لائف پال ایک معلوماتی ساتھی ہے۔ یہ آپ کو تشخیص نہیں دے گا۔',
  no_prescription_title: 'کوئی نسخہ نہیں',
  no_prescription_desc: 'AI کبھی بھی دوا کی مخصوص خوراک کا مشورہ نہیں دیتا ہے۔',
  amu_grounded_title: 'ادارہ جاتی بنیاد',
  amu_grounded_desc: 'تمام علاقائی مشورے JNMCH، علی گڑھ کے پروٹوکول پر مبنی ہیں۔',
  ai_ethics_title: 'ذہین مدد',
  data_sovereignty_title: 'ڈیٹا کی خودمختاری',
  financial_transparency_title: 'براہ راست امداد کا بہاؤ',
  pediatric_sanctuary_title: 'بچوں کی پناہ گاہ',
  impact_patients_supported: 'مریض جن کی مدد کی گئی',
  impact_care_interactions: 'نگہداشت کی بات چیت',
  impact_mental_health: 'ذہنی صحت کا چیک ان',
  impact_navigation: 'نیویگیشن سیشنز',
  impact_kindness_title: 'آپ کی ہمدردی کی طاقت',
  impact_hero_ways: 'ہیرو بننے کے طریقے',
  impact_sponsor_title: 'علاج کی کفالت کریں',
  impact_sponsor_desc: 'فنڈز کی کمی کی وجہ سے بہت سے مریض کیمو روک دیتے ہیں۔ آپ کا عطیہ زندگی بچانے والی ادویات خریدتا ہے۔',
  impact_gift_life: 'زندگی کا تحفہ',
  impact_gift_life_desc: 'کیموتھراپی پلیٹلیٹس کو کم کرتی ہے۔ آپ کے خون کا ایک یونٹ 3 مریضوں کی جان بچا سکتا ہے۔',
  impact_share_warmth: 'محبت بانٹیں',
  impact_share_warmth_desc: 'وارڈوں میں سردیاں مشکل ہوتی ہیں۔ کمبل یا غذائی سپلیمنٹس عطیہ کریں۔',
  impact_active_zones: 'فعال امدادی زون',
  impact_milestones: 'آپ کے سنگ میل',
  emergency_immediate_action: 'فوری کارروائی (پہلے 5 منٹ)',
  emergency_key_numbers: 'اہم نمبر',
  emergency_red_folder: '"ریڈ فولڈر" چیک لسٹ',
  emergency_prevention: 'روک تھام کی چوکسی',
  nav_clinical_id: 'طبی شناخت کار (کینسر کی قسم)',
  nav_location: 'علاقائی سیاق و سباق (مقام)',
  nav_priority: 'ذہانت کی ترجیح منتخب کریں',
  nav_launch: 'نیویگیٹر لانچ کریں',
  nav_strategy: 'تیار کردہ حکمت عملی',
  nav_institutional: 'ادارہ جاتی امداد',
  nav_strategic_facilities: 'تزویراتی سہولیات'
};

const TE_STRINGS = {
  dashboard: 'డ్యాష్‌బోర్డ్',
  mood_board: 'మూడ్ బోర్డ్',
  navigator: 'నేవిగేటర్',
  navigator_header: 'కేర్ నేవిగేటర్',
  navigator_sub: 'క్లినికల్ రోడ్‌మ్యాప్ మరియు వనరుల సమాచారం.',
  med_scanner: 'మెడిసిన్ స్కానర్',
  meds_scanner_header: 'Vision AI-MedScanner',
  meds_scanner_sub: 'మందుల గుర్తింపు, మోతాదు అంతర్దృష్టులు మరియు భద్రతా మార్గదర్శకత్వం.',
  doc_intel: 'డాక్ ఇంటెల్',
  doc_intel_header: 'డాక్ ఇంటెల్ వాల్ట్',
  doc_intel_sub: 'రిపోర్టులను అజూర్ వాల్ట్‌లో భద్రపరచండి.',
  insights: 'జ్ఞాన కేంద్రం',
  insights_header: 'జ్ఞాన కేంద్రం',
  insights_sub: 'క్లినికల్ వార్తలు మరియు నిపుణుల మార్గదర్శకాలు.',
  meetups: 'సర్వైవర్ మీటప్స్',
  trust: 'నమ్మకం',
  hero_hub: 'హీరో హెడ్ క్వార్టర్స్',
  hero_garden: 'హీరో గార్డెన్',
  hero_tasks: 'పవర్ టాస్క్లు',
  emergency_sos: 'అత్యవసర SOS',
  emergency_prep: 'క్రైసిస్ గార్డ్',
  emergency_header: 'క్రైసిస్ గార్డ్',
  emergency_sub: 'క్యాన్సర్ అత్యవసర పరిస్థితుల కోసం కీలక ప్రోటోకాల్‌లు.',
  impact_hub: 'ప్రభావ కేంద్రం',
  impact_hub_header: 'ప్రభావ కేంద్రం',
  impact_hub_sub: 'సామాజిక ప్రభావాన్ని చూడండి మరియు మద్దతు ఇవ్వండి.',
  welcome: 'స్వాగతం',
  give_aid: 'సహాయం అందించండి',
  nursing_aid: 'నర్సింగ్ సహాయం',
  settings: 'సెట్టింగులు',
  companion: 'ఏఐ తోడు',
  finder: 'అన్వేషకుడు',
  finder_header: 'వనరుల అన్వేషకుడు',
  finder_sub: 'సమీపంలోని ఫార్మసీ మరియు క్యాన్సర్ కేంద్రాలను కనుగొండి.',
  schemes: 'సహాయ పథకాలు',
  schemes_header: 'సహాయ పథకాలు',
  schemes_sub: 'ప్రభుత్వ సహాయం మరియు ఆర్థిక పథకాలు.',
  survivors_hub: 'సర్వైవర్స్ హబ్',
  survivors_hub_header: 'సర్వైవర్స్ హబ్',
  survivors_hub_sub: 'క్యాన్సర్ తర్వాత మీ ప్రయాణం.',
  skills_hub: 'నైపుణ్య కేంద్రం',
  skills_hub_header: 'క్లినికల్ స్కిల్స్ హబ్',
  skills_hub_sub: 'ఏఐ ట్యుటోరియల్స్‌తో సంరక్షణ నేర్చుకోండి.',
  saved_sanctuary: 'భద్రపరచిన నిలయం',
  saved_sanctuary_header: 'భద్రపరచిన నిలయం',
  saved_sanctuary_sub: 'మీరు సేవ్ చేసిన వనరులు.',
  welcome_home: 'ఇంటికి స్వాగతం మిత్రమా',
  unified_sanctuary: 'ఏకీకృత కేర్ హబ్',
  comfort_recovery_desc: 'కోలుకోవడం కోసం సులభమైన సాధనాలు.',
  clinical_logic_desc: 'క్లినికల్ మరియు భావోద్వేగ మద్దతు కోసం ఒక సున్నితమైన నిలయం.',
  gen_brief: 'డాక్టర్ బ్రీఫ్ తయారు చేయండి',
  search_placeholder: 'వెతకండి...',
  select_perspective: 'మీ దృక్పథాన్ని ఎంచుకోండి',
  select_desc: 'మీ ప్రయాణాన్ని ఎంచుకోండి, మేము మీకు సహాయం చేస్తాము.',
  role_patient: 'రోగి',
  role_caregiver: 'సంరక్షకుడు',
  role_hero: 'హీరో పిల్లాడు',
  role_donor: 'మద్దతుదారు',
  role_survivor: 'సర్వైవర్',
  role_patient_desc: 'క్లినికల్ నావిగేషన్ మరియు సులభమైన గైడ్‌లు.',
  role_caregiver_desc: 'కుటుంబం కోసం పూర్తి వనరుల కేంద్రం.',
  role_hero_desc: 'బడ్డీ ఏఐ తోడుతో ఒక గేమిఫైడ్ మ్యాజిక్ క్వెస్ట్.',
  role_donor_desc: 'సామాజిక ప్రభావాన్ని చూడండి మరియు మద్దతు ఇవ్వండి.',
  role_survivor_desc: 'క్యాన్సర్ తర్వాత ఫాలో-అప్ గైడ్‌లు.',
  news_tab: 'వార్తలు',
  guides_tab: 'గైడ్లు',
  portals_tab: 'పోర్టల్స్',
  back: 'వెనక్కి',
  continue: 'కొనసాగించు',
  save: 'సేవ్ చేయి',
  add: 'జత చేయి',
  delete: 'తొలగించు',
  logout: 'లాగ్ అవుట్',
  sync: 'సింక్ చేయి',
  buddy_chat: 'బడ్డీతో మాట్లాడండి',
  buddy_desc: 'మీ మాయా ఏఐ స్నేహితుడు',
  hero_quests: 'సూపర్ క్వెస్టలు',
  hero_quest_banner: 'హీరో క్వెస్ట్',
  hero_welcome: 'హీరో హెడ్ క్వార్టర్స్‌కు స్వాగతం!',
  hero_level: 'హీరో స్థాయి',
  magic_energy_needed: 'తదుపరి పవర్-అప్ కోసం ఎక్స్‌పీ',
  memory_quest: 'మెమరీ క్వెస్ట్',
  train_brain: 'మెదడుకు శిక్షణ ఇవ్వండి',
  magic_studio: 'మ్యాజిక్ స్టూడియో',
  open_studio: 'స్టూడియో తెరవండి',
  mystery_box: 'మిస్టరీ బాక్స్',
  mystery_box_title: 'మిస్టరీ బాక్స్!',
  mystery_box_desc: 'లోపల ఒక ప్రత్యేక హీరో నిధి దాగి ఉంది. చూడాలనుకుంటున్నారా?',
  tap_to_open: 'తెరవడానికి నొక్కండి',
  unlocked: 'తెరిచారు',
  sticker_vault: 'స్టిక్కర్ వాల్ట్',
  collected: 'సేకరించినవి',
  magic_fact: 'మాయా నిజం',
  hero_cinema: 'హీరో సినిమా',
  cinema_banner: 'మీ కోలుకునే మిషన్ కోసం మాయా క్షణాలు.',
  stay_brave: 'ధైర్యంగా ఉండండి',
  magic_energy: 'మాయా శక్తి',
  symptom_log: 'లక్షణాల లాగ్',
  symptom_log_header: 'లక్షణాల లాగ్',
  symptom_log_sub: 'శారీరక మార్పులను ట్రాక్ చేయండి.',
  scan_history: 'స్కాన్ చరిత్ర',
  add_reminder: 'రిమైండర్ జత చేయి',
  analyzing: 'విశ్లేషిస్తోంది...',
  analyze_symptoms: 'నమూనాలను విశ్లేషించండి',
  generating_insights: 'ధోరణులను కనుగొంటోంది...',
  symptom_patterns_header: 'లక్షణ ఇంటెలిజెన్స్',
  symptom_patterns_sub: 'క్లినికల్ నమూనాలను కనుగొనండి.',
  daily_sanctuary_focus: 'రోజువారీ ఫోకస్',
  completed: 'పూర్తయింది',
  mark_complete: 'పూర్తయినట్లు గుర్తించండి',
  open_now: 'ఇప్పుడే తెరువు',
  later: 'తర్వాత',
  new_sticker: 'కొత్త స్టిక్కర్!',
  bravery_sparkle: 'మీ ధైర్యానికి ఒక కొత్త మెరుపు వచ్చింది!',
  xp_awarded: 'XP అందించబడింది',
  level_up: 'లేవల్ అప్!',
  reached_level: 'స్థాయికి చేరుకున్నారు',
  continue_quest: 'క్వెస్ట్ కొనసాగించండి',
  transparency: 'పారదర్శకత',
  transparency_title: 'ట్రస్ట్ & ఎథిక్స్ సెంటర్',
  transparency_desc: 'లైఫ్‌పాల్ నైతిక AI, సంస్థాగత విశ్వాసం మరియు సమాజ భద్రత పునాదిపై నిర్మించబడింది.',
  medical_guardrails: 'మెడికల్ గార్డ్‌రైల్స్',
  no_diagnosis_title: 'రోగనిర్ధారణ లేదు',
  no_diagnosis_desc: 'లైఫ్‌పాల్ ఒక సమాచార తోడు మాత్రమే. ఇది మీకు రోగనిర్ధారణ చేయదు.',
  no_prescription_title: 'ప్రిస్క్రిప్షన్ లేదు',
  no_prescription_desc: 'AI ఎప్పుడూ మందుల మోతాదులను సూచించదు.',
  amu_grounded_title: 'సంస్థాగత పునాది',
  amu_grounded_desc: 'అన్ని ప్రాంతీయ సలహాలు JNMCH, అలీఘర్ ప్రోటోకాల్‌లపై ఆధారపడి ఉంటాయి.',
  ai_ethics_title: 'మేధో సహాయం',
  data_sovereignty_title: 'డేటా సార్వభౌమాధికారం',
  financial_transparency_title: 'ప్రత్యక్ష సహాయ ప్రవాహం',
  pediatric_sanctuary_title: 'పీడియాట్రిక్ శాంక్చురీ',
  impact_patients_supported: 'మద్దతు పొందిన రోగులు',
  impact_care_interactions: 'సంరక్షణ పరస్పర చర్యలు',
  impact_mental_health: 'మానసిక ఆరోగ్య చెక్-ఇన్‌లు',
  impact_navigation: 'నేవిగేషన్ సెషన్‌లు',
  impact_kindness_title: 'మీ దయ యొక్క శక్తి',
  impact_hero_ways: 'హీరో కావడానికి మార్గాలు',
  impact_sponsor_title: 'చికిత్సకు స్పాన్సర్ చేయండి',
  impact_sponsor_desc: 'నిధుల కొరత వల్ల చాలా మంది రోగులు కీమోను ఆపివేస్తారు. మీ విరాళం మందులను కొనుగోలు చేస్తుంది.',
  impact_gift_life: 'జీవన ప్రవాహాన్ని బహుమతిగా ఇవ్వండి',
  impact_gift_life_desc: 'కీమోథెరపీ ప్లేట్‌లెట్స్‌ను తగ్గిస్తుంది. మీ రక్తం ఒక యూనిట్ 3 మంది రోగులను కాపాడుతుంది.',
  impact_share_warmth: 'వెచ్చదనాన్ని పంచుకోండి',
  impact_share_warmth_desc: 'వార్డులలో చలికాలం కష్టంగా ఉంటుంది. దుప్పట్లు లేదా పోషకాహార పదార్ధాలను దానం చేయండి.',
  impact_active_zones: 'క్రియాశీల మద్దతు మండలాలు',
  impact_milestones: 'మీ మైలురాళ్లు',
  emergency_immediate_action: 'తక్షణ చర్య (మొదటి 5 నిమిషాలు)',
  emergency_key_numbers: 'ముఖ్యమైన సంఖ్యలు',
  emergency_red_folder: '"రెడ్ ఫోల్డర్" చెక్‌లిస్ట్',
  emergency_prevention: 'నివారణ అప్రమత్తత',
  nav_clinical_id: 'క్లినికల్ ఐడెంటిఫైయర్ (క్యాన్సర్ రకం)',
  nav_location: 'ప్రాంతీయ సందర్భం (స్థలం)',
  nav_priority: 'మేధస్సు ప్రాధాన్యతను ఎంచుకోండి',
  nav_launch: 'నేవిగేటర్‌ను ప్రారంభించండి',
  nav_strategy: 'రూపొందించిన వ్యూహం',
  nav_institutional: 'సంస్థాగత ఉపశమనం',
  nav_strategic_facilities: 'వ్యూహాత్మక సౌకర్యాలు'
};

export const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  [AppLanguage.ENGLISH]: EN_STRINGS,
  [AppLanguage.HINDI]: HI_STRINGS,
  [AppLanguage.URDU]: UR_STRINGS,
  [AppLanguage.TELUGU]: TE_STRINGS
};

export interface TrustedPortal {
  id: string;
  title: string;
  description: string;
  url: string;
  category: string;
  tag: string;
  thumbnail: string;
}

export const TRUSTED_RESOURCES: TrustedPortal[] = [
  {
    id: 'macmillan-cancer-support',
    title: 'Macmillan Cancer Support',
    description: 'Expert information on physical, emotional and financial support for cancer patients in the UK and worldwide.',
    url: 'https://www.macmillan.org.uk/',
    category: 'Support',
    tag: 'PATIENT_WELLNESS',
    thumbnail: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'national-cancer-institute',
    title: 'National Cancer Institute',
    description: 'The US government\'s principal agency for cancer research and training. Groundbreaking research and verified data.',
    url: 'https://www.cancer.gov/',
    category: 'Research',
    tag: 'RESEARCH_LEADER',
    thumbnail: 'https://images.unsplash.com/photo-1581056771107-24ca5f033842?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'who-cancer',
    title: 'WHO Cancer Portal',
    description: 'Global authority on cancer prevention, control and international health protocols.',
    url: 'https://www.who.int/health-topics/cancer',
    category: 'Global',
    tag: 'GLOBAL_STANDARD',
    thumbnail: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'tata-memorial',
    title: 'Tata Memorial Centre',
    description: 'India\'s premier cancer research and treatment institution based in Mumbai.',
    url: 'https://tmc.gov.in/',
    category: 'Hospital',
    tag: 'INDIA_EXCELLENCE',
    thumbnail: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'alig-care-main',
    title: 'ALIG CARE Support',
    description: 'Regional coordination hub for oncology patients at JNMCH AMU Aligarh.',
    url: 'https://aligscare.org/',
    category: 'Regional',
    tag: 'ALIGARH_LOCAL',
    thumbnail: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'st-jude',
    title: 'St. Jude Children Research',
    description: 'Leading global resource for pediatric oncology research and specialized child care.',
    url: 'https://www.stjude.org/',
    category: 'Research',
    tag: 'PEDIATRIC_EXCELLENCE',
    thumbnail: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'mskcc-ny',
    title: 'MSK Cancer Center',
    description: 'Specialized protocols and breakthrough treatment news from New York.',
    url: 'https://www.mskcc.org/',
    category: 'Clinical',
    tag: 'TREATMENT_INNOVATION',
    thumbnail: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'acs-org',
    title: 'American Cancer Society',
    description: 'Patient advocacy, screening guidelines, and community support resources.',
    url: 'https://www.cancer.org/',
    category: 'Policy',
    tag: 'ADVOCACY_LEADER',
    thumbnail: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'mayo-clinic',
    title: 'Mayo Clinic Oncology',
    description: 'World-renowned medical research and care guidelines for complex oncology cases.',
    url: 'https://www.mayoclinic.org/tests-procedures/cancer-treatment/about/pac-20385127',
    category: 'Clinical',
    tag: 'CLINICAL_LEADER',
    thumbnail: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800'
  }
];

export const SCHEMES: Scheme[] = [
  {
    id: 'pm-nrf',
    name: 'PM National Relief Fund (PMNRF)',
    description: 'Immediate relief for medical treatments like cancer, heart surgery, and kidney transplants for those in financial distress.',
    eligibility: ['Citizens in extreme financial hardship', 'Verified by the Prime Minister Office'],
    documents: ['Medical estimate from hospital', 'Income certificate', 'Identity proof', 'Photographs'],
    steps: ['Obtain medical estimate from JNMCH Superintendent', 'Apply via the PMO portal or regional MP', 'Wait for sanction letter'],
    officialUrl: 'https://pmnrf.gov.in/',
    type: 'GOVERNMENT',
    fundType: 'PM_CARE'
  },
  {
    id: 'up-cm-relief',
    name: 'UP CM Relief Fund',
    description: 'Discretionary financial assistance for residents of Uttar Pradesh facing critical health challenges.',
    eligibility: ['Permanent residents of Uttar Pradesh', 'BPL or verified low-income status'],
    documents: ['Aadhaar Card (UP Address)', 'Income Certificate (Tehsildar)', 'Estimate from Government Hospital'],
    steps: ['Submit estimate to the DM office', 'Verification by Chief Medical Officer', 'Funds released to the hospital account'],
    officialUrl: 'http://up.gov.in/',
    type: 'GOVERNMENT',
    fundType: 'CM_CARE'
  },
  {
    id: 'hmcpf-ran',
    name: 'Health Minister Cancer Patient Fund (HMCPF/RAN)',
    description: 'Financial assistance for patients living below poverty line for treatment in designated government hospitals.',
    eligibility: ['Patients with income below ₹1.25 Lakh per annum', 'Treatment in empaneled Govt hospitals'],
    documents: ['Income Proof', 'Ration Card', 'Treatment Estimate (Counter-signed by HOD Oncology)'],
    steps: ['Fill the RAN application at the hospital helpdesk', 'Get counter-signature from Oncology Dept', 'Submit to MoHFW'],
    officialUrl: 'https://mohfw.gov.in/major-programmes/poor-patients-financial-assistance/rashtriya-arogya-nidhi',
    type: 'GOVERNMENT',
    fundType: 'PM_CARE'
  },
  {
    id: 'ayushman-bharat',
    name: 'Ayushman Bharat (PM-JAY)',
    description: 'World\'s largest health insurance scheme providing ₹5 Lakh cover per family per year.',
    eligibility: ['SECC Database listed families', 'Low-income households'],
    documents: ['Ayushman Card / Golden Card', 'Aadhaar Card'],
    steps: ['Check eligibility on PM-JAY website', 'Visit the Ayushman Mitra kiosk at JNMCH', 'Get pre-authorization'],
    officialUrl: 'https://pmjay.gov.in/',
    type: 'GOVERNMENT',
    fundType: 'AYUSHMAN'
  },
  {
    id: 'esi-scheme',
    name: 'ESI Scheme (Oncology Coverage)',
    description: 'Comprehensive health coverage for employees and their dependents with access to specialized cancer treatment.',
    eligibility: ['Registered employees earning up to ₹21,000/month', 'Dependents of ESI card holders'],
    documents: ['ESI Pehchan Card', 'Employment certification', 'Medical referral from ESI dispensary'],
    steps: ['Visit local ESI dispensary', 'Get referral to an empaneled private oncology wing', 'Avail cashless treatment'],
    officialUrl: 'https://www.esic.gov.in/',
    type: 'GOVERNMENT',
    fundType: 'PM_CARE'
  },
  {
    id: 'hmdg-grant',
    name: 'Health Minister Discretionary Grant',
    description: 'Grant of up to ₹1.25 lakh for patients in financial need to cover cost of medicines and diagnostics.',
    eligibility: ['Low-income patients not covered under PM-JAY', 'Treatment at major Govt hospitals'],
    documents: ['Identity Proof', 'Income Certificate', 'Clinical justification from treating doctor'],
    steps: ['Collect grant application from Hospital Superintendent', 'Get HOD oncology signature', 'Submit to MoHFW'],
    officialUrl: 'https://www.mohfw.gov.in/?q=en/major-programmes/poor-patients-financial-assistance/health-ministers-discretionary-grant-hmdg',
    type: 'GOVERNMENT',
    fundType: 'PM_CARE'
  },
  {
    id: 'alig-care-aid',
    name: 'ALIG CARE Support',
    description: 'Regional foundation providing direct pharmaceutical and diagnostic aid for oncology patients at JNMCH AMU Aligarh.',
    eligibility: ['Patients undergoing treatment at JNMCH', 'Verified clinical distress'],
    documents: ['OPD/IPD Card', 'Prescription', 'Estimate from Alig Care Desk'],
    steps: ['Visit the Alig Care desk at the Oncology wing', 'Verification by the coordinating officer', 'Direct pharmacy billing settlement'],
    officialUrl: 'https://aligscare.org/',
    type: 'INSTITUTIONAL',
    fundType: 'ALIG_CARE'
  }
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp-101',
    title: 'Support Life-Saving Surgery for Zoya',
    patientName: 'Zoya Khan',
    targetAmount: 350000,
    raisedAmount: 120000,
    category: 'MEDICAL',
    story: 'Zoya needs immediate surgery for a growing tumor. Her father is a daily wage worker in Aligarh.',
    impactStory: 'Funds will directly cover hospital stay and surgery costs at JNMCH.',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1505751172107-573225a943d0?auto=format&fit=crop&q=80&w=800',
    donationsCount: 142
  },
  {
    id: 'camp-102',
    title: 'Chemotherapy Fund for Master Aman',
    patientName: 'Aman Sharma',
    targetAmount: 200000,
    raisedAmount: 185000,
    category: 'MEDICAL',
    story: 'Aman is a 12-year-old braveheart undergoing his final cycles of chemo.',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800',
    donationsCount: 89
  }
];

export const CHILD_VIDEOS: ChildVideo[] = [
  {
    id: 'vid-1',
    title: 'The Brave Knight Story',
    description: 'A beautiful story about courage and inner strength.',
    youtubeId: 'wY-kAnvOY80',
    videoUrl: '',
    externalUrl: '',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=800',
    category: 'Hero Story'
  },
  {
    id: 'vid-2',
    title: 'Calm Kids Meditation',
    description: 'Gently find your magic center and peaceful breath.',
    youtubeId: '0I647Gu70S8',
    videoUrl: '',
    externalUrl: '',
    thumbnail: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=800',
    category: 'Peace Quest'
  },
  {
    id: 'vid-3',
    title: 'Cosmic Kids Yoga',
    description: 'Join the adventure and build your hero power.',
    youtubeId: 'Z0A_e4F92Sg',
    videoUrl: '',
    externalUrl: '',
    thumbnail: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=800',
    category: 'Hero Power'
  },
  {
    id: 'vid-4',
    title: 'The Hungry Caterpillar',
    description: 'A classic tale of growth and transformation.',
    youtubeId: 'vYpSIs07W20',
    videoUrl: '',
    externalUrl: '',
    thumbnail: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&q=80&w=800',
    category: 'Magic Nature'
  }
];

export const VERIFIED_GUIDES: Article[] = [
  {
    id: 'guide-chemo-diet',
    title: 'Optimal Diet During Chemotherapy',
    summary: 'Evidence-based nutritional advice to manage appetite loss and nausea.',
    content: 'Full content here...',
    category: 'LIFESTYLE',
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&q=80&w=800',
    tags: ['Nutrition', 'Chemo'],
    link: 'https://www.cancer.gov/about-cancer/treatment/side-effects/appetite-loss/nutrition-pdq'
  },
  {
    id: 'guide-home-hygiene',
    title: 'Maintaining a Neutropenic Home',
    summary: 'Critical steps for keeping your environment safe for loved ones.',
    content: 'Full content here...',
    category: 'SYMPTOMS',
    imageUrl: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?auto=format&fit=crop&q=80&w=800',
    tags: ['Safety', 'Hygiene'],
    link: 'https://www.mskcc.org/cancer-care/patient-education/neutropenia-low-white-blood-cell-count'
  },
  {
    id: 'guide-fatigue-mgt',
    title: 'Preserving Energy (Fatigue)',
    summary: 'Mastering the art of pacing and active rest during long treatment cycles.',
    content: '',
    category: 'LIFESTYLE',
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800',
    tags: ['Rest', 'Fatigue'],
    link: 'https://www.macmillan.org.uk/cancer-information-and-support/impacts-of-cancer/fatigue'
  },
  {
    id: 'guide-palliative-care',
    title: 'Understanding Supportive Care',
    summary: 'How palliative services improve the quality of life for patients and families.',
    content: '',
    category: 'EMOTIONAL',
    imageUrl: 'https://images.unsplash.com/photo-1518152006812-edab29b069ac?auto=format&fit=crop&q=80&w=800',
    tags: ['Palliative', 'Comfort'],
    link: 'https://www.who.int/news-room/fact-sheets/detail/palliative-care'
  },
  {
    id: 'guide-mental-calm',
    title: 'Mental Health: Finding Calm',
    summary: 'Cognitive strategies and gentle meditation practices for diagnoses anxiety.',
    content: '',
    category: 'EMOTIONAL',
    imageUrl: 'https://images.unsplash.com/photo-1516585427167-9f4af9627e6c?auto=format&fit=crop&q=80&w=800',
    tags: ['Mindfulness', 'Stress'],
    link: 'https://www.cancer.org/cancer/survivorship/coping/emotional-well-being.html'
  },
  {
    id: 'guide-financial-planning',
    title: 'Financial Planning for Care',
    summary: 'Practical steps to organize medical documents for faster scheme approval.',
    content: '',
    category: 'SCHEMES',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=800',
    tags: ['Planning', 'Aid'],
    link: 'https://www.macmillan.org.uk/cancer-information-and-support/impacts-of-cancer/financial-impact-of-cancer'
  },
  {
    id: 'guide-sleep-recovery',
    title: 'Sleep Hygiene Post-Infusion',
    summary: 'Optimizing the sleep environment for repair after chemotherapy.',
    content: '',
    category: 'LIFESTYLE',
    imageUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&q=80&w=800',
    tags: ['Sleep', 'Recovery'],
    link: 'https://www.cancer.org/cancer/survivorship/coping/sleep-problems.html'
  },
  {
    id: 'guide-communication-tips',
    title: 'Talking to Your Clinical Team',
    summary: 'Mastering the art of describing symptoms accurately to ensure your team has data.',
    content: '',
    category: 'SYMPTOMS',
    imageUrl: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?auto=format&fit=crop&q=80&w=800',
    tags: ['Communication', 'Advocacy'],
    link: 'https://www.cancer.gov/about-cancer/coping/adjusting-to-cancer/communication'
  }
];
