
import { Scheme, Campaign, Article, SupportGroup, ChildVideo, AppEvent, AppLanguage } from './types';

const EN_STRINGS = {
  dashboard: 'Dashboard',
  mood_board: 'Mood Board',
  navigator: 'Navigator',
  navigator_header: 'Visionary Care Navigator',
  navigator_sub: 'Precision-mapped clinical roadmaps integrated with institutional protocols.',
  med_scanner: 'Meds Scanner',
  meds_scanner_header: 'Vision-AI Med Scanner',
  meds_scanner_sub: 'Grounded pharmaceutical analysis of chemical compounds and safety warnings.',
  doc_intel: 'Doc Intel',
  doc_intel_header: 'Doc Intel Vault',
  doc_intel_sub: 'Securely store reports in Azure Vault and let AI explain context.',
  insights: 'Insights Hub',
  insights_header: 'Insights Hub',
  insights_sub: 'Clinical news verified portals and expert guides.',
  meetups: 'Survivor Meetups',
  trust: 'Trust',
  hero_hub: 'Hero HQ',
  hero_garden: 'Hero Garden',
  hero_tasks: 'Power Tasks',
  emergency_sos: 'EMERGENCY SOS',
  emergency_prep: 'Crisis Guard',
  emergency_header: 'Crisis Readiness Guard',
  emergency_sub: 'Critical protocols and identification checklists for oncology emergencies.',
  impact_hub: 'Impact Hub',
  impact_hub_header: 'Impact Hub',
  impact_hub_sub: 'Witness social impact and support care navigation.',
  welcome: 'Welcome',
  give_aid: 'Support Impact',
  nursing_aid: 'Nursing Aid',
  settings: 'Settings',
  companion: 'AI Companion',
  finder: 'Finder',
  finder_header: 'Resource Finder',
  finder_sub: 'Locate oncology resources and nearby pharmacies.',
  schemes: 'Aid Schemes',
  schemes_header: 'Aid Schemes',
  schemes_sub: 'Navigate government paperwork with ease. Verified financial aid.',
  survivors_hub: 'Survivors Hub',
  survivors_hub_header: 'Survivors Hub',
  survivors_hub_sub: 'Your Resilience Sanctuary for life after cancer.',
  skills_hub: 'Skills Hub',
  skills_hub_header: 'Clinical Skills Hub',
  skills_hub_sub: 'Master home-care tasks with AI-guided tutorials.',
  saved_sanctuary: 'Saved Sanctuary',
  saved_sanctuary_header: 'Saved Sanctuary',
  saved_sanctuary_sub: 'Your curated collection of important guides and resources.',
  welcome_home: 'Welcome Home Friend',
  unified_sanctuary: 'Unified Care Sanctuary',
  comfort_recovery_desc: 'Easy to use tools for your comfort and recovery.',
  clinical_logic_desc: 'A gentle sanctuary for clinical logic and emotional resilience.',
  gen_brief: 'Generate Doctor Brief',
  search_placeholder: 'Search Sanctuary...',
  select_perspective: 'Select your Perspective',
  select_desc: 'Choose your journey so we can personalize every bit of support.',
  role_patient: 'Patient',
  role_caregiver: 'Caregiver',
  role_hero: 'Hero Kid',
  role_donor: 'Supporter',
  role_survivor: 'Survivor',
  role_patient_desc: 'Clinical navigation, nursing aid, and easy read guides.',
  role_caregiver_desc: 'Full resource hub for guardians and family support.',
  role_hero_desc: 'A gamified magic quest with Buddy the hero companion.',
  role_donor_desc: 'Witness social impact and support care navigation.',
  role_survivor_desc: 'Follow up monitoring and life after cancer guides.',
  news_tab: 'News',
  guides_tab: 'Guides',
  portals_tab: 'Portals',
  back: 'Back',
  continue: 'Continue',
  save: 'Save',
  add: 'Add',
  delete: 'Delete',
  logout: 'Logout',
  sync: 'Sync',
  buddy_chat: 'Talk to Buddy',
  buddy_desc: 'Your magic AI friend',
  hero_quests: 'Super Quests',
  hero_quest_banner: 'The Hero Quest',
  hero_welcome: 'Welcome to Hero HQ!',
  hero_level: 'Hero Level',
  magic_energy_needed: 'XP to Next Power-up',
  memory_quest: 'Memory Quest',
  train_brain: 'Train Your Brain',
  magic_studio: 'Magic Studio',
  open_studio: 'Open Studio',
  mystery_box: 'Mystery Box',
  mystery_box_title: 'The Mystery Box!',
  mystery_box_desc: 'A special hero treasure is hidden inside. Want to see it?',
  tap_to_open: 'Tap to Open',
  unlocked: 'Unlocked',
  sticker_vault: 'Sticker Vault',
  collected: 'Collected',
  magic_fact: 'Magic Fact',
  hero_cinema: 'Hero Cinema',
  cinema_banner: 'Magic moments and brave stories for your recovery mission.',
  stay_brave: 'Stay Brave',
  magic_energy: 'Magic Energy',
  symptom_log: 'Symptom Log',
  symptom_log_header: 'Symptom Log',
  symptom_log_sub: 'Track physical changes to share with your oncology team.',
  scan_history: 'Scan History',
  add_reminder: 'Add Reminder',
  analyzing: 'Analyzing Medicine...',
  analyze_symptoms: 'Analyze Patterns',
  generating_insights: 'Finding Trends...',
  symptom_patterns_header: 'Symptom Intelligence',
  symptom_patterns_sub: 'Discover clinical patterns in your log.',
  daily_sanctuary_focus: 'Daily Sanctuary Focus',
  completed: 'Completed',
  mark_complete: 'Mark Complete',
  open_now: 'Open Now',
  later: 'Later',
  new_sticker: 'New Sticker!',
  bravery_sparkle: 'Your bravery just got a new sparkle!',
  xp_awarded: 'XP Awarded',
  level_up: 'Level Up!',
  reached_level: 'Reached Level',
  continue_quest: 'Continue Quest'
};

const HI_STRINGS = {
  dashboard: 'डैशबोर्ड',
  mood_board: 'मूड बोर्ड',
  navigator: 'नेविगेटर',
  navigator_header: 'केयर नेविगेटर',
  navigator_sub: 'संस्थागत प्रोटोकॉल के साथ सटीक क्लीनिकल रोडमैप।',
  med_scanner: 'दवा स्कैनर',
  meds_scanner_header: 'विज़न-AI मेड स्कैनर',
  meds_scanner_sub: 'दवाओं के रासायनिक घटकों और सुरक्षा चेतावनियों का एआई विश्लेषण।',
  doc_intel: 'डॉक इंटेल',
  doc_intel_header: 'डॉक इंटेल वॉल्ट',
  doc_intel_sub: 'रिपोर्ट सुरक्षित रूप से एज़्योर वॉल्ट में स्टोर करें।',
  insights: 'इनसाइट्स हब',
  insights_header: 'इनसाइट्स हब',
  insights_sub: 'सत्यापित समाचार और विशेषज्ञ गाइड।',
  meetups: 'सर्वाइवर मीटअप',
  trust: 'ट्रस्ट',
  hero_hub: 'हीरो मुख्यालय',
  hero_garden: 'हीरो गार्डन',
  hero_tasks: 'पावर टास्क',
  emergency_sos: 'आपातकालीन SOS',
  emergency_prep: 'क्राइसिस गार्ड',
  emergency_header: 'क्राइसिस गार्ड',
  emergency_sub: 'कैंसर आपात स्थितियों के लिए महत्वपूर्ण प्रोटोकॉल।',
  impact_hub: 'इम्पैक्ट हब',
  impact_hub_header: 'इम्पैक्ट हब',
  impact_hub_sub: 'सामाजिक प्रभाव देखें और मदद करें।',
  welcome: 'स्वागत है',
  give_aid: 'सहायता दें',
  nursing_aid: 'नर्सिंग सहायता',
  settings: 'सेटिंग्स',
  companion: 'एआई साथी',
  finder: 'खोजक',
  finder_header: 'संसाधन खोजक',
  finder_sub: 'नजदीकी फार्मेसी और कैंसर संसाधनों का पता लगाएं।',
  schemes: 'सहायता योजनाएं',
  schemes_header: 'सहायता योजनाएं',
  schemes_sub: 'सरकारी सहायता को आसानी से नेविगेट करें।',
  survivors_hub: 'सर्वाइवर्स हब',
  survivors_hub_header: 'सर्वाइवर्स हब',
  survivors_hub_sub: 'कैंसर के बाद जीवन के लिए आपका सुरक्षित स्थान।',
  skills_hub: 'कौशल हब',
  skills_hub_header: 'क्लीनिकल स्किल्स हब',
  skills_hub_sub: 'एआई ट्यूटोरियल के साथ घर पर देखभाल सीखें।',
  saved_sanctuary: 'सुरक्षित स्थान',
  saved_sanctuary_header: 'सुरक्षित स्थान',
  saved_sanctuary_sub: 'आपके द्वारा सहेजे गए महत्वपूर्ण गाइड और संसाधन।',
  welcome_home: 'घर में स्वागत है दोस्त',
  unified_sanctuary: 'एकीकृत केयर हब',
  comfort_recovery_desc: 'आपकी रिकवरी के लिए आसान टूल।',
  clinical_logic_desc: 'क्लीनिकल तर्क और भावनात्मक मजबूती के लिए एक कोमल स्थान।',
  gen_brief: 'डॉक्टर ब्रीफ बनाएं',
  search_placeholder: 'खोजें...',
  select_perspective: 'अपना दृष्टिकोण चुनें',
  select_desc: 'अपनी यात्रा चुनें ताकि हम आपकी सहायता कर सकें।',
  role_patient: 'मरीज',
  role_caregiver: 'देखभाल करने वाला',
  role_hero: 'हीरो बच्चा',
  role_donor: 'समर्थक',
  role_survivor: 'सर्वाइवर',
  role_patient_desc: 'क्लीनिकल नेविगेशन और आसान गाइड।',
  role_caregiver_desc: 'परिवार के लिए पूर्ण संसाधन हब।',
  role_hero_desc: 'बडी एआई साथी के साथ एक जादुई खोज।',
  role_donor_desc: 'सामाजिक प्रभाव देखें और देखभाल में मदद करें।',
  role_survivor_desc: 'कैंसर के बाद जीवन के लिए फॉलो-अप गाइड।',
  news_tab: 'समाचार',
  guides_tab: 'गाइड',
  portals_tab: 'पोर्टल',
  back: 'पीछे',
  continue: 'जारी रखें',
  save: 'सहेजें',
  add: 'जोड़ें',
  delete: 'हटाएं',
  logout: 'लॉगआउट',
  sync: 'सिंक',
  buddy_chat: 'बडी से बात करें',
  buddy_desc: 'आपका जादुई एआई दोस्त',
  hero_quests: 'सुपर क्वेस्ट',
  hero_quest_banner: 'हीरो क्वेस्ट',
  hero_welcome: 'हीरो मुख्यालय में आपका स्वागत है!',
  hero_level: 'हीरो स्तर',
  magic_energy_needed: 'अगले पावर-अप के लिए XP',
  memory_quest: 'मेमोरी क्वेस्ट',
  train_brain: 'दिमाग को ट्रेन करें',
  magic_studio: 'मैजिक स्टूडियो',
  open_studio: 'स्टूडियो खोलें',
  mystery_box: 'मिस्ट्री बॉक्स',
  mystery_box_title: 'मिस्ट्री बॉक्स!',
  mystery_box_desc: 'अंदर एक विशेष खजाना छिपा है। देखना चाहते हैं?',
  tap_to_open: 'खोलने के लिए टैप करें',
  unlocked: 'खुल गया',
  sticker_vault: 'स्टिकर वॉल्ट',
  collected: 'एकत्रित',
  magic_fact: 'जादुई तथ्य',
  hero_cinema: 'हीरो सिनेमा',
  cinema_banner: 'आपकी रिकवरी के लिए जादुई पल और कहानियाँ।',
  stay_brave: 'बहादुर रहें',
  magic_energy: 'जादुई ऊर्जा',
  symptom_log: 'लक्षण लॉग',
  symptom_log_header: 'लक्षण लॉग',
  symptom_log_sub: 'शारीरिक परिवर्तनों को ट्रैक करें।',
  scan_history: 'स्कैन इतिहास',
  add_reminder: 'रिमाइंडर जोड़ें',
  analyzing: 'दवा का विश्लेषण हो रहा है...',
  analyze_symptoms: 'पैटर्न विश्लेषण',
  generating_insights: 'रुझान ढूँढना...',
  symptom_patterns_header: 'लक्षण इंटेलिजेंस',
  symptom_patterns_sub: 'अपने लॉग में क्लीनिकल पैटर्न खोजें।',
  daily_sanctuary_focus: 'दैनिक फोकस',
  completed: 'पूरा हुआ',
  mark_complete: 'पूरा चिह्नित करें',
  open_now: 'अभी खोलें',
  later: 'बाद में',
  new_sticker: 'नया स्टिकर!',
  bravery_sparkle: 'आपकी बहादुरी में एक नई चमक आ गई है!',
  xp_awarded: 'XP मिला',
  level_up: 'लेवल अप!',
  reached_level: 'स्तर पर पहुँच गए',
  continue_quest: 'क्वेस्ट जारी रखें'
};

const UR_STRINGS = {
  dashboard: 'ڈیش بورڈ',
  mood_board: 'موڈ بورڈ',
  navigator: 'نیویگیٹر',
  navigator_header: 'کیئر نیویگیٹر',
  navigator_sub: 'طبی روڈ میپ اور وسائل کی معلومات۔',
  med_scanner: 'میڈ اسکینر',
  meds_scanner_header: 'ویژن اے آئی میڈ اسکینر',
  meds_scanner_sub: 'دواؤں کا اے آئی تجزیہ۔',
  doc_intel: 'دستاویز انٹیل',
  doc_intel_header: 'دستاویز انٹیل والٹ',
  doc_intel_sub: 'رپورٹس کو ایزیور والٹ میں محفوظ کریں۔',
  insights: 'بصیرت مرکز',
  insights_header: 'بصیرت مرکز',
  insights_sub: 'طبی خبریں اور ماہر گائیڈز।',
  meetups: 'سروائیور ملاقاتیں',
  trust: 'بھروسہ',
  hero_hub: 'ہیرو ہیڈ کوارٹر',
  hero_garden: 'ہیرو گارڈن',
  hero_tasks: 'پاور ٹاسک',
  emergency_sos: 'ہنگامی SOS',
  emergency_prep: 'کرائسس گارڈ',
  emergency_header: 'کرائسس گارڈ',
  emergency_sub: 'کینسر کی ہنگامی صورتحال کے لیے پروٹوکول۔',
  impact_hub: 'اثر مرکز',
  impact_hub_header: 'اثر مرکز',
  impact_hub_sub: 'سماجی اثر دیکھیں اور مدد کریں۔',
  welcome: 'خوش آمدید',
  give_aid: 'مدد کریں',
  nursing_aid: 'نرسنگ مدد',
  settings: 'ترتیبات',
  companion: 'اے آئی ساتھی',
  finder: 'تلاش کار',
  finder_header: 'وسائل تلاش کریں',
  finder_sub: 'قریبی فارمیسی اور طبی مراکز تلاش کریں۔',
  schemes: 'امدادی اسکیمیں',
  schemes_header: 'امدادی اسکیمیں',
  schemes_sub: 'سرکاری مدد اور فنڈز کی معلومات۔',
  survivors_hub: 'سروائیورز مرکز',
  survivors_hub_header: 'سروائیورز مرکز',
  survivors_hub_sub: 'صحت یابی کے بعد کا سفر۔',
  skills_hub: 'ہنر مرکز',
  skills_hub_header: 'کلینیکل ہنر مرکز',
  skills_hub_sub: 'گھر پر دیکھ بھال کے طریقے سیکھیں۔',
  saved_sanctuary: 'محفوظ پناہ گاہ',
  saved_sanctuary_header: 'محفوظ پناہ گاہ',
  saved_sanctuary_sub: 'آپ کے محفوظ کردہ وسائل।',
  welcome_home: 'خوش آمدید دوست',
  unified_sanctuary: 'یونیفائیڈ کیئر ہب',
  comfort_recovery_desc: 'صحت یابی کے لیے آسان ٹولز।',
  clinical_logic_desc: 'طبی اور جذباتی مدد کے لیے ایک نرم جگہ।',
  gen_brief: 'ڈاکٹر بریف تیار کریں',
  search_placeholder: 'تلاش کریں...',
  select_perspective: 'اپنا نقطہ نظر منتخب کریں',
  select_desc: 'اپنا سفر منتخب کریں تاکہ ہم مدد کر سکیں۔',
  role_patient: 'مریض',
  role_caregiver: 'نگہداشت کنندہ',
  role_hero: 'ہیرو بچہ',
  role_donor: 'معاون',
  role_survivor: 'سروائیور',
  role_patient_desc: 'طبی نیویگیشن اور آسان گائیڈز।',
  role_caregiver_desc: 'خاندان کے لیے مکمل وسائل مرکز।',
  role_hero_desc: 'بڈی اے آئی ساتھی کے ساتھ ایک جادوئی مشن।',
  role_donor_desc: 'سماجی اثر دیکھیں اور مدد فراہم کریں۔',
  role_survivor_desc: 'صحت یابی کے بعد کی نگرانی।',
  news_tab: 'خبریں',
  guides_tab: 'گائیڈز',
  portals_tab: 'پورٹلز',
  back: 'واپس',
  continue: 'جاری رکھیں',
  save: 'محفوظ کریں',
  add: 'شامل کریں',
  delete: 'حذف کریں',
  logout: 'لاگ آؤٹ',
  sync: 'مطابقت پذیری',
  buddy_chat: 'بڈی سے بات کریں',
  buddy_desc: 'آپ کا جادوئی اے آئی دوست',
  hero_quests: 'سپر کوئسٹس',
  hero_quest_banner: 'ہیرو مشن',
  hero_welcome: 'ہیرو ہیڈ کوارٹر में خوش آمدید!',
  hero_level: 'ہیرو کی سطح',
  magic_energy_needed: 'ایکس پی درکار ہے',
  memory_quest: 'یادداشت کا مشن',
  train_brain: 'دماغ کو تربیت دیں',
  magic_studio: 'جادو اسٹوڈیو',
  open_studio: 'اسٹوڈیو کھولیں',
  mystery_box: 'پراسرار باکس',
  mystery_box_title: 'پراسرار باکس!',
  mystery_box_desc: 'اندر ایک خاص خزانہ چھپا ہے۔ دیکھنا چاہتے ہیں؟',
  tap_to_open: 'کھولنے کے لیے دبائیں',
  unlocked: 'کھول دیا گیا',
  sticker_vault: 'اسٹیکر والٹ',
  collected: 'جمع شدہ',
  magic_fact: 'جادوئی حقیقت',
  hero_cinema: 'ہیرو سنیما',
  cinema_banner: 'آپ کی صحت یابی کے مشن کے لیے جادوئی لمحات।',
  stay_brave: 'بہادر رہیں',
  magic_energy: 'جادوئی توانائی',
  symptom_log: 'علامات کا لاگ',
  symptom_log_header: 'علامات کا لاگ',
  symptom_log_sub: 'جسمانی تبدیلیوں کو ٹریک کریں۔',
  scan_history: 'اسکین کی تاریخ',
  add_reminder: 'یاد دہانی شامل کریں',
  analyzing: 'تجزیہ ہو رہا ہے...',
  analyze_symptoms: 'پیٹرن کا تجزیہ کریں',
  generating_insights: 'بصیرتیں تلاش کی جا رہی ہیں...',
  symptom_patterns_header: 'علامات کی ذہانت',
  symptom_patterns_sub: 'اپنے لاگ میں طبی پیٹرن دریافت کریں۔',
  daily_sanctuary_focus: 'روزانہ کی توجہ',
  completed: 'مکمل ہو گیا',
  mark_complete: 'مکمل نشان زد کریں',
  open_now: 'ابھی کھولیں',
  later: 'بعد میں',
  new_sticker: 'نیا اسٹیکر!',
  bravery_sparkle: 'آپ کی بہادری میں ایک نئی چمک آگئی ہے!',
  xp_awarded: 'XP مل گیا',
  level_up: 'لیول اپ!',
  reached_level: 'سطح پر پہنچ گئے',
  continue_quest: 'مشن جاری رکھیں'
};

const TE_STRINGS = {
  dashboard: 'డ్యాష్‌బోర్డ్',
  mood_board: 'మూడ్ బోర్డ్',
  navigator: 'నేవిగేటర్',
  navigator_header: 'కేర్ నేవిగేటర్',
  navigator_sub: 'క్లినికల్ రోడ్‌మ్యాప్ మరియు వనరుల సమాచారం.',
  med_scanner: 'మెడిసిన్ స్కానర్',
  meds_scanner_header: 'విజన్-AI మెడ్ స్కానర్',
  meds_scanner_sub: 'ఔషధాల యొక్క ఏఐ విశ్లేషణ.',
  doc_intel: 'డాక్ ఇంటెల్',
  doc_intel_header: 'డాక్ ఇంటెల్ వాల్ట్',
  doc_intel_sub: 'రిపోర్టులను అజూర్ వాల్ట్‌లో భద్రపరచండి.',
  insights: 'జ్ఞాన కేంద్రం',
  insights_header: 'జ్ఞాన కేంద్రం',
  insights_sub: 'క్లినికల్ వార్తలు మరియు నిపుణుల మార్గదర్శకాలు.',
  meetups: 'సర్వైవర్ మీటప్స్',
  trust: 'నమ్మకం',
  hero_hub: 'హీరో హెడ్ క్వార్టర్స్',
  hero_garden: 'హీరో గార్డెన్',
  hero_tasks: 'పవర్ టాస్క్లు',
  emergency_sos: 'అత్యవసర SOS',
  emergency_prep: 'క్రైసిస్ గార్డ్',
  emergency_header: 'క్రైసిస్ గార్డ్',
  emergency_sub: 'క్యాన్సర్ అత్యవసర పరిస్థితుల కోసం కీలక ప్రోటోకాల్‌లు.',
  impact_hub: 'ప్రభావ కేంద్రం',
  impact_hub_header: 'ప్రభావ కేంద్రం',
  impact_hub_sub: 'సామాజిక ప్రభావాన్ని చూడండి మరియు మద్దతు ఇవ్వండి.',
  welcome: 'స్వాగతం',
  give_aid: 'సహాయం అందించండి',
  nursing_aid: 'నర్సింగ్ సహాయం',
  settings: 'సెట్టింగులు',
  companion: 'ఏఐ తోడు',
  finder: 'అన్వేషకుడు',
  finder_header: 'వనరుల అన్వేషకుడు',
  finder_sub: 'సమీపంలోని ఫార్మసీ మరియు క్యాన్సర్ కేంద్రాలను కనుగొండి.',
  schemes: 'సహాయ పథకాలు',
  schemes_header: 'సహాయ పథకాలు',
  schemes_sub: 'ప్రభుత్వ సహాయం మరియు ఆర్థిక పథకాలు.',
  survivors_hub: 'సర్వైవర్స్ హబ్',
  survivors_hub_header: 'సర్వైవర్స్ హబ్',
  survivors_hub_sub: 'క్యాన్సర్ తర్వాత మీ ప్రయాణం.',
  skills_hub: 'నైపుణ్య కేంద్రం',
  skills_hub_header: 'క్లినికల్ స్కిల్స్ హబ్',
  skills_hub_sub: 'ఏఐ ట్యుటోరియల్స్‌తో సంరక్షణ నేర్చుకోండి.',
  saved_sanctuary: 'భద్రపరచిన నిలయం',
  saved_sanctuary_header: 'భద్రపరచిన నిలయం',
  saved_sanctuary_sub: 'మీరు సేవ్ చేసిన వనరులు.',
  welcome_home: 'ఇంటికి స్వాగతం మిత్రమా',
  unified_sanctuary: 'ఏకీకృత కేర్ హబ్',
  comfort_recovery_desc: 'కోలుకోవడం కోసం సులభమైన సాధనాలు.',
  clinical_logic_desc: 'క్లినికల్ మరియు భావోద్వేగ మద్దతు కోసం ఒక సున్నితమైన నిలయం.',
  gen_brief: 'డాక్టర్ బ్రీఫ్ తయారు చేయండి',
  search_placeholder: 'వెతకండి...',
  select_perspective: 'మీ దృక్పథాన్ని ఎంచుకోండి',
  select_desc: 'మీ ప్రయాణాన్ని ఎంచుకోండి, మేము మీకు సహాయం చేస్తాము.',
  role_patient: 'రోగి',
  role_caregiver: 'సంరక్షకుడు',
  role_hero: 'హీరో పిల్లాడు',
  role_donor: 'మద్దతుదారు',
  role_survivor: 'సర్వైవర్',
  role_patient_desc: 'క్లినికల్ నావిగేషన్ మరియు సులభమైన గైడ్‌లు.',
  role_caregiver_desc: 'కుటుంబం కోసం పూర్తి వనరుల కేంద్రం.',
  role_hero_desc: 'బడ్డీ ఏఐ తోడుతో ఒక గేమిఫైడ్ మ్యాజిక్ క్వెస్ట్.',
  role_donor_desc: 'సామాజిక ప్రభావాన్ని చూడండి మరియు మద్దతు ఇవ్వండి.',
  role_survivor_desc: 'క్యాన్సర్ తర్వాత ఫాలో-అప్ గైడ్‌లు.',
  news_tab: 'వార్తలు',
  guides_tab: 'గైడ్లు',
  portals_tab: 'పోర్టల్స్',
  back: 'వెనక్కి',
  continue: 'కొనసాగించు',
  save: 'సేవ్ చేయి',
  add: 'జత చేయి',
  delete: 'తొలగించు',
  logout: 'లాగ్ అవుట్',
  sync: 'సింక్ చేయి',
  buddy_chat: 'బడ్డీతో మాట్లాడండి',
  buddy_desc: 'మీ మాయా ఏఐ స్నేహితుడు',
  hero_quests: 'సూపర్ క్వెస్ట్‌లు',
  hero_quest_banner: 'హీరో క్వెస్ట్',
  hero_welcome: 'హీరో హెడ్ క్వార్టర్స్‌కు స్వాగతం!',
  hero_level: 'హీరో స్థాయి',
  magic_energy_needed: 'తదుపరి పవర్-అప్ కోసం ఎక్స్‌పీ',
  memory_quest: 'మెమరీ క్వెస్ట్',
  train_brain: 'మెదడుకు శిక్షణ ఇవ్వండి',
  magic_studio: 'మ్యాజిక్ స్టూడియో',
  open_studio: 'స్టూడియో తెరవండి',
  mystery_box: 'మిస్టరీ బాక్స్',
  mystery_box_title: 'మిస్టరీ బాక్స్!',
  mystery_box_desc: 'లోపల ఒక ప్రత్యేక హీరో నిధి దాగి ఉంది. చూడాలనుకుంటున్నారా?',
  tap_to_open: 'తెరవడానికి నొక్కండి',
  unlocked: 'తెరిచారు',
  sticker_vault: 'స్టిక్కర్ వాల్ట్',
  collected: 'సేకరించినవి',
  magic_fact: 'మాయా నిజం',
  hero_cinema: 'హీరో సినిమా',
  cinema_banner: 'మీ కోలుకునే మిషన్ కోసం మాయా క్షణాలు.',
  stay_brave: 'ధైర్యంగా ఉండండి',
  magic_energy: 'మాయా శక్తి',
  symptom_log: 'లక్షణాల లాగ్',
  symptom_log_header: 'లక్షణాల లాగ్',
  symptom_log_sub: 'శారీరక మార్పులను ట్రాక్ చేయండి.',
  scan_history: 'స్కాన్ చరిత్ర',
  add_reminder: 'రిమైండర్ జత చేయి',
  analyzing: 'విశ్లేషిస్తోంది...',
  analyze_symptoms: 'నమూనాలను విశ్లేషించండి',
  generating_insights: 'ధోరణులను కనుగొంటోంది...',
  symptom_patterns_header: 'లక్షణ ఇంటెలిజెన్స్',
  symptom_patterns_sub: 'క్లినికల్ నమూనాలను కనుగొనండి.',
  daily_sanctuary_focus: 'రోజువారీ ఫోకస్',
  completed: 'పూర్తయింది',
  mark_complete: 'పూర్తయినట్లు గుర్తించండి',
  open_now: 'ఇప్పుడే తెరువు',
  later: 'తర్వాత',
  new_sticker: 'కొత్త స్టిక్కర్!',
  bravery_sparkle: 'మీ ధైర్యానికి ఒక కొత్త మెరుపు వచ్చింది!',
  xp_awarded: 'XP అందించబడింది',
  level_up: 'లేవల్ అప్!',
  reached_level: 'స్థాయికి చేరుకున్నారు',
  continue_quest: 'క్వెస్ట్ కొనసాగించండి'
};

export const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  [AppLanguage.ENGLISH]: EN_STRINGS,
  [AppLanguage.HINDI]: HI_STRINGS,
  [AppLanguage.URDU]: UR_STRINGS,
  [AppLanguage.TELUGU]: TE_STRINGS
};

export const CHILD_VIDEOS: ChildVideo[] = [
  {
    id: 'vid-bluey',
    title: 'Bluey: Bumpy and the Wise Old Wolfhound',
    description: 'Bluey learns about staying in the hospital through a funny and heartwarming home movie.',
    youtubeId: 'pS-Wz9zDqH0',
    videoUrl: '',
    externalUrl: 'https://youtu.be/pS-Wz9zDqH0',
    thumbnail: 'https://img.youtube.com/vi/pS-Wz9zDqH0/maxresdefault.jpg',
    category: 'Magic Story'
  },
  {
    id: 'vid-coco',
    title: 'Coco: Remember Me',
    description: 'A beautiful musical story about family love and the strength of memories.',
    youtubeId: '3iDxU6hSps0',
    videoUrl: '',
    externalUrl: 'https://youtu.be/3iDxU6hSps0',
    thumbnail: 'https://img.youtube.com/vi/3iDxU6hSps0/maxresdefault.jpg',
    category: 'Heart Songs'
  },
  {
    id: 'vid-hero',
    title: 'Big Hero 6: Healing Power',
    description: 'Baymax shows that care and kindness are the greatest superpowers of all.',
    youtubeId: 'T8XmH4F7A6A',
    videoUrl: '',
    externalUrl: 'https://youtu.be/T8XmH4F7A6A',
    thumbnail: 'https://img.youtube.com/vi/T8XmH4F7A6A/maxresdefault.jpg',
    category: 'Hero Quest'
  },
  {
    id: 'vid-calm',
    title: 'Calm Breathing for Little Heroes',
    description: 'Follow the glowing light to find your calm inner strength.',
    youtubeId: 'aNXKjGF_0tE',
    videoUrl: '',
    externalUrl: 'https://youtu.be/aNXKjGF_0tE',
    thumbnail: 'https://img.youtube.com/vi/aNXKjGF_0tE/maxresdefault.jpg',
    category: 'Calm Power'
  },
  {
    id: 'vid-inside-out',
    title: 'Inside Out: Joy and Sadness',
    description: 'Understanding that all feelings are okay and help us be brave.',
    youtubeId: 'QT9fGz6C6qM',
    videoUrl: '',
    externalUrl: 'https://youtu.be/QT9fGz6C6qM',
    thumbnail: 'https://img.youtube.com/vi/QT9fGz6C6qM/maxresdefault.jpg',
    category: 'Magic Feelings'
  }
];

export const SCHEMES: Scheme[] = [
  {
    id: 'ayushman_bharat',
    name: 'Ayushman Bharat (PM-JAY)',
    description: 'The world\'s largest health insurance scheme fully financed by the government, providing ₹5 Lakh cover per family.',
    eligibility: ['Socio-economic Caste Census (SECC) families', 'Low-income households', 'BPL card holders'],
    documents: ['Aadhaar Card', 'Ration Card', 'Mobile Number', 'BPL Card'],
    steps: ['Check eligibility on PM-JAY portal', 'Visit empaneled hospital (JNMCH)', 'Verify identity at Ayushman kiosk'],
    officialUrl: 'https://pmjay.gov.in/',
    type: 'GOVERNMENT',
    fundType: 'AYUSHMAN'
  },
  {
    id: 'alig_care_fund',
    name: 'ALIG CARE Support (ACF)',
    description: 'Regional fund supporting oncology patients at JNMCH Aligarh.',
    eligibility: ['Students and local Aligarh residents', 'Verified financial distress'],
    documents: ['Student ID (if applicable)', 'JNMCH OPD card', 'Verified income docs'],
    steps: ['Meet ACF social worker at JNMCH', 'Documentation review', 'Direct pharmacy credit'],
    officialUrl: 'https://aligscare.org/',
    type: 'INSTITUTIONAL',
    fundType: 'ALIG_CARE'
  }
];

export const TRUSTED_RESOURCES = [
  {
    id: 'who-cancer',
    title: 'WHO Cancer Portal',
    description: 'Global authority on cancer prevention, control and international health protocols.',
    url: 'https://www.who.int/health-topics/cancer',
    category: 'Global',
    tag: 'GLOBAL_STANDARD'
  },
  {
    id: 'nci-usa',
    title: 'National Cancer Institute',
    description: 'Comprehensive research and treatment information from the US National Institutes of Health.',
    url: 'https://www.cancer.gov/',
    category: 'Research',
    tag: 'RESEARCH_LEADER'
  },
  {
    id: 'tata-memorial',
    title: 'Tata Memorial Centre',
    description: 'India\'s premier cancer research and treatment institution based in Mumbai.',
    url: 'https://tmc.gov.in/',
    category: 'Hospital',
    tag: 'INDIA_EXCELLENCE'
  },
  {
    id: 'alig-care-main',
    title: 'ALIG CARE Support',
    description: 'Regional coordination hub for oncology patients at JNMCH AMU Aligarh.',
    url: 'https://aligscare.org/',
    category: 'Regional',
    tag: 'ALIGARH_LOCAL'
  },
  {
    id: 'mayo-clinic',
    title: 'Mayo Clinic',
    description: 'World-renowned medical research and care guidelines for complex oncology cases.',
    url: 'https://www.mayoclinic.org/tests-procedures/cancer-treatment/about/pac-20385127',
    category: 'Clinical',
    tag: 'CLINICAL_LEADER'
  }
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp_1',
    title: 'Support Aman\'s Lymphoma Treatment',
    patientName: 'Aman K.',
    targetAmount: 500000,
    raisedAmount: 320000,
    category: 'MEDICAL',
    story: 'Aman is a student from Aligarh battling stage 3 lymphoma. Help him complete his chemotherapy.',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=800',
    donationsCount: 142
  }
];

export const VERIFIED_GUIDES: Article[] = [
  {
    id: 'guide-1',
    title: 'Preparing for Chemotherapy',
    summary: 'A step-by-step guide on what to bring and how to prepare mentally.',
    content: '',
    category: 'LIFESTYLE',
    imageUrl: 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&q=80&w=800',
    tags: ['Chemo', 'Recovery'],
    link: '#'
  }
];
